In [1]:
import numpy as np
import pandas as pd
import random

# Data Understanding

In [2]:
products_data_csv = pd.read_csv("scraped_product_data.csv")
products_data_csv.head(15)

,Product Name,Product Category,Product Brand,Product Price,Product Description
0,Panasonic 23 L Convection Microwave Oven,Kitchen Appliances,Panasonic,"₹9,790","Control Type: Touch Key Pad (Membrane),Child L..."
1,Panasonic 27 L Convection Microwave Oven,Kitchen Appliances,Panasonic,"₹10,990","Control Type: Touch Key Pad (Membrane),1 year ..."
2,IFB 23 L Convection Microwave Oven,Kitchen Appliances,IFB,"₹10,790","Control Type: Touch Key Pad (Membrane),Child L..."
3,SAMSUNG 23 L Grill Microwave Oven,Kitchen Appliances,SAMSUNG,"₹8,399","Control Type: Tact (Buttons), Jog Dial"
4,Panasonic 20 L Solo Microwave Oven,Kitchen Appliances,Panasonic,"₹5,790",Control Type: Touch Key Pad (Membrane)
5,LG 20 L with i-wave Technology Solo Microwave ...,Kitchen Appliances,LG,"₹6,890","Control Type: Touch Key Pad (Membrane),Manufac..."
6,"SAMSUNG 28 L Curd Making, A Perfect Gift With ...",Kitchen Appliances,SAMSUNG,"₹12,290","Control Type: Touch Key Pad (Membrane),Child L..."
7,"SAMSUNG 21 L Triple Distribution System, A Per...",Kitchen Appliances,SAMSUNG,"₹9,990","Control Type: Touch Key Pad (Membrane),Child L..."
8,SAMSUNG 23 L Solo Microwave Oven,Kitchen Appliances,SAMSUNG,"₹7,390",Control Type: Tact (Buttons)
9,IFB 20 L Solo Microwave Oven,Kitchen Appliances,IFB,"₹6,490","Control Type: Jog Dial,1 Year Product Warranty..."
10,LG 20 L with i-wave Technology & Quartz Heater...,Kitchen Appliances,LG,"₹7,889","Control Type: Touch Key Pad (Membrane),Child L..."
11,"LG 28 L with Diet Fry, 360 Motorised Rotisseri...",Kitchen Appliances,LG,"₹15,990","Control Type: Tact (Buttons),Child Lock Presen..."
12,"LG 32 L with Diet Fry, 360 Motorised Rotisseri...",Kitchen Appliances,LG,"₹17,990","Control Type: Tact (Buttons),Child Lock Presen..."
13,"SAMSUNG 32 L Slim Fry, Curd Making, A Perfect ...",Kitchen Appliances,SAMSUNG,"₹16,290","Control Type: Tact (Buttons), Jog Dial,1 Year ..."
14,IFB 30 L Convection Microwave Oven,Kitchen Appliances,IFB,"₹15,390","Control Type: Touch Key Pad (Membrane),Child L..."

In [3]:
# Shuffle the DataFrame
products_data = products_data_csv.sample(frac=1, random_state=42).reset_index(drop=True)
products_data.insert(0, 'product_id', range(1, len(products_data) + 1))

In [4]:
products_data.head(15)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
0,1,"Apple iPhone 15 (Pink, 512 GB)",Mobiles,Apple,"₹87,999","512 GB ROM,15.49 cm (6.1 inch) Super Retina XD..."
1,2,"vivo Y22 (Starlit Blue, 64 GB)",Mobiles,vivo,"₹14,499","4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
2,3,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",Mobiles,SAMSUNG,"₹1,08,999","12 GB RAM | 256 GB ROM,17.27 cm (6.8 inch) Qua..."
3,4,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",Mobiles,SAMSUNG,"₹24,790","8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
4,5,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",Mobiles,SAMSUNG,"₹8,999","4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) HD+ D..."
5,6,SAMSUNG 123 cm (49 inch) Full HD LED TV,Televisions,SAMSUNG,"₹55,099","Full HD 1920 x 1080 Pixels,Launch Year: 2016,1..."
6,7,"SAMSUNG Galaxy S21 FE 5G (Lavender, 128 GB)",Mobiles,SAMSUNG,"₹39,999","8 GB RAM | 128 GB ROM,16.26 cm (6.4 inch) Full..."
7,8,"SAMSUNG Galaxy M13 (Aqua Green, 128 GB)",Mobiles,SAMSUNG,"₹13,999","6 GB RAM | 128 GB ROM,16.76 cm (6.6 inch) Disp..."
8,9,"vivo X70 Pro (Aurora Dawn, 256 GB)",Mobiles,vivo,"₹39,825","12 GB RAM | 256 GB ROM,16.66 cm (6.56 inch) Fu..."
9,10,"Nokia 106 4G Keypad Mobile, Long-Lasting Batte...",Mobiles,Nokia,"₹2,235","32 MB RAM | 32 MB ROM,4.5 cm (1.77 inch) Displ..."
10,11,"vivo Y100A (Twilight Gold, 256 GB)",Mobiles,vivo,"₹23,999","8 GB RAM | 256 GB ROM,16.21 cm (6.38 inch) Ful..."
11,12,"Apple iPhone 16 (White, 128 GB)",Mobiles,Apple,"₹79,900","128 GB ROM,15.49 cm (6.1 inch) Super Retina XD..."
12,13,"vivo Y17s (Glitter Purple, 128 GB)",Mobiles,vivo,"₹10,900","4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
13,14,"Google Pixel 7a (Snow, 128 GB)",Mobiles,Google,"₹31,999","8 GB RAM | 128 GB ROM,15.49 cm (6.1 inch) Full..."
14,15,"vivo T3 Lite 5G (Vibrant Green, 128 GB)",Mobiles,vivo,"₹10,499","4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."

In [5]:
products_data.shape

(1541, 6)

In [6]:
raw_users = [
    {'user_id': 1, 'user_name': 'Mohit', 'email': 'mohit07@gmail.com'},
    {'user_id': 2, 'user_name': 'Amitesh', 'email': 'amitesh03@gmail.com'},
    {'user_id': 3, 'user_name': 'Virat', 'email': 'virat18@gmail.com'},
    {'user_id': 4, 'user_name': 'Roman', 'email': 'roman01@gmail.com'}
]
users = pd.DataFrame(raw_users)

In [7]:
users.head()

   user_id user_name                email
0        1     Mohit    mohit07@gmail.com
1        2   Amitesh  amitesh03@gmail.com
2        3     Virat    virat18@gmail.com
3        4     Roman    roman01@gmail.com

In [8]:
# users.to_csv('users.csv', index=False)

# Creating User Interest Data

In [9]:
# Parameters
num_users = 4   # Number of users
num_products = 1541  # Number of products
num_interactions = 256  # Number of interactions to generate 4**4

# Generate user IDs
user_ids = [i for i in range(1, num_users + 1)]
# Generate product IDs
product_ids = [i for i in range(1, num_products + 1)]
# Create an empty list to hold interactions
interactions = []

for _ in range(num_interactions):
    user_id = random.choice(user_ids)
    product_id = random.choice(product_ids)
    rating = random.choice([1, 2, 3, 4, 5])  # Ratings from 1 to 5 or None
    
    interactions.append({
        'user_id': user_id,
        'product_id': product_id,
        'rating': rating
    })

# Create a DataFrame from the interactions list
interaction_df = pd.DataFrame(interactions)

# Optionally, you can reset the index for better readability
interaction_df.reset_index(drop=True, inplace=True)

In [10]:
interaction_df.sample(15)

     user_id  product_id  rating
242        1         224       1
120        3         500       2
196        1         857       3
203        2        1465       3
13         1         932       5
144        2         919       4
106        2        1352       1
121        4         624       1
160        2          64       4
76         4         626       5
27         3        1345       1
162        4         501       3
186        2         158       4
150        4        1454       2
100        1         618       2

In [11]:
products_data_copy = products_data.copy()

In [12]:
products_data_copy.head()

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
0,1,"Apple iPhone 15 (Pink, 512 GB)",Mobiles,Apple,"₹87,999","512 GB ROM,15.49 cm (6.1 inch) Super Retina XD..."
1,2,"vivo Y22 (Starlit Blue, 64 GB)",Mobiles,vivo,"₹14,499","4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
2,3,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",Mobiles,SAMSUNG,"₹1,08,999","12 GB RAM | 256 GB ROM,17.27 cm (6.8 inch) Qua..."
3,4,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",Mobiles,SAMSUNG,"₹24,790","8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
4,5,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",Mobiles,SAMSUNG,"₹8,999","4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) HD+ D..."

In [13]:
# 1 mohit ->mobiles(vivo,samsung,<25000) | speakers(jbl,sony,boAt)

In [14]:
products_data_copy['Product Category'].unique()

array(['Mobiles', 'Televisions', 'Kitchen Appliances', 'Speakers'],
      dtype=object)

In [15]:
products_data_copy['Product Brand'].unique()

array(['Apple', 'vivo', 'SAMSUNG', 'Nokia', 'Google', 'LG', 'SONY',
       'OnePlus', 'POCO', 'Mi', 'Landmark', 'IFB', 'OPPO', 'boAt', 'Mivi',
       'Panasonic', 'Samsung', 'JBL', 'Portronics'], dtype=object)

In [16]:
speaker_brands = products_data_copy[products_data_copy['Product Category'] == 'Speakers']
speaker_brands.head()

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
41,42,Landmark LM BS117 Portable Home TV Soundbar wi...,Speakers,Landmark,₹899,"Power Output(RMS): 20 W,Battery life: 6 hr | C..."
66,67,"boAt Aavante Bar A1040 w/ Attractive Design, E...",Speakers,boAt,"₹3,999","Power Output(RMS): 50 W,Bluetooth Version: 5.3..."
84,85,"Mivi Fort S16 with 2 full range drivers, Made ...",Speakers,Mivi,"₹1,099","Power Output(RMS): 16 W,Power Source: 5V DC Ty..."
159,160,Landmark LM BS117 Portable Home TV Soundbar wi...,Speakers,Landmark,₹899,"Power Output(RMS): 20 W,Battery life: 6 hr | C..."
239,240,Landmark LM BS117 Portable Home TV Soundbar wi...,Speakers,Landmark,₹899,"Power Output(RMS): 20 W,Battery life: 6 hr | C..."

In [17]:
speakers_data_1 = products_data_copy[
    (products_data_copy['Product Category'] == 'Speakers') &
    (products_data_copy['Product Brand'].isin(['JBL','SONY','boAt']))
]
print(speakers_data_1.shape)
speakers_data_1.head()

(17, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
66,67,"boAt Aavante Bar A1040 w/ Attractive Design, E...",Speakers,boAt,"₹3,999","Power Output(RMS): 50 W,Bluetooth Version: 5.3..."
361,362,"boAt Aavante Bar 5500DA w/ Dolby Atmos,Wireles...",Speakers,boAt,"₹16,999","Power Output(RMS): 500 W,Wireless music stream..."
405,406,"JBL Cinema SB240 2.1 with Remote, Dolby Digita...",Speakers,JBL,"₹6,998","Power Output(RMS): 110 W,Power Source: AC Adap..."
588,589,"boAt Aavante Bar 590 with RMS, Dual Passive Ra...",Speakers,boAt,"₹1,699","Power Output(RMS): 25 W,Wireless music streami..."
670,671,boAt Blitz 2000 Multimedia 100 W Bluetooth Hom...,Speakers,boAt,"₹3,999","Power Output(RMS): 100 W,Bluetooth Version: 5,..."

In [18]:
products_data_copy['Product Price'] = products_data_copy['Product Price'].replace(
    {'Not Available': np.nan}
)
products_data_copy['Product Price'] = (
    products_data_copy['Product Price']
    .replace('[₹,]', '', regex=True)
    .astype(float)  # Convert to float (handles decimals if any)
)

mobile_data_1 = products_data_copy[
    (products_data_copy['Product Category'] == 'Mobiles') &
    (products_data_copy['Product Brand'].isin(['SAMSUNG', 'vivo'])) &
    (products_data_copy['Product Price'] < 25000)
]
print(mobile_data_1.shape)
mobile_data_1.head()

(288, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
1,2,"vivo Y22 (Starlit Blue, 64 GB)",Mobiles,vivo,14499.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
3,4,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",Mobiles,SAMSUNG,24790.0,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
4,5,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",Mobiles,SAMSUNG,8999.0,"4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) HD+ D..."
7,8,"SAMSUNG Galaxy M13 (Aqua Green, 128 GB)",Mobiles,SAMSUNG,13999.0,"6 GB RAM | 128 GB ROM,16.76 cm (6.6 inch) Disp..."
10,11,"vivo Y100A (Twilight Gold, 256 GB)",Mobiles,vivo,23999.0,"8 GB RAM | 256 GB ROM,16.21 cm (6.38 inch) Ful..."

In [19]:
user_1_data = interaction_df[interaction_df['user_id'] == 1]
user_1_data.shape

(53, 3)

In [20]:
def update_interaction_with_product_ids(interaction_df, user_id, *product_id_lists):
    """
    Updates the interaction_df with product IDs for a specified user_id.
    
    Parameters:
    - interaction_df: DataFrame containing interactions
    - user_id: The user ID to update in interaction_df
    - product_id_lists: A variable number of product ID lists
    
    Returns:
    - Updated interaction_df
    """
    # Step 1: Combine all provided product ID lists and shuffle them
    combined_product_ids = []
    for product_id_list in product_id_lists:
        combined_product_ids.extend(product_id_list)
    
    random.shuffle(combined_product_ids)
    
    # Step 2: Filter the interactions for the specified user_id
    user_interactions = interaction_df[interaction_df['user_id'] == user_id]
    num_user_interactions = len(user_interactions)
    
    # Step 3: Adjust combined_product_ids based on the number of user interactions
    if len(combined_product_ids) < num_user_interactions:
        # If there are not enough product IDs, repeat them to fill
        combined_product_ids = (
            combined_product_ids * (num_user_interactions // len(combined_product_ids) + 1)
        )[:num_user_interactions]
    else:
        # If there are more product IDs than needed, take only the required number
        combined_product_ids = combined_product_ids[:num_user_interactions]
    
    # Step 4: Update interaction_df with the selected product IDs for the specified user_id
    interaction_df.loc[interaction_df['user_id'] == user_id, 'product_id'] = combined_product_ids
    
    return interaction_df

In [21]:
interaction_df = update_interaction_with_product_ids(
    interaction_df,  # Positional argument
    1,  # Positional argument for user_id
    mobile_data_1['product_id'].tolist(),  # Positional argument
    speakers_data_1['product_id'].tolist(),  # Positional argument
)

In [22]:
user_1_product_details = interaction_df[interaction_df['user_id'] == 1].merge(products_data_copy, on='product_id', how='left')
print(user_1_product_details['Product Category'].unique())
user_1_product_details.sample(25)

['Mobiles' 'Speakers']

,user_id,product_id,rating,Product Name,Product Category,Product Brand,Product Price,Product Description
31,1,930,1,"vivo Y58 5G (Sundarbans Green, 128 GB)",Mobiles,vivo,18369.0,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
2,1,298,5,"SAMSUNG Galaxy M35 5G (DayBreak Blue, 128 GB)",Mobiles,SAMSUNG,18869.0,"8 GB RAM | 128 GB ROM,16.76 cm (6.6 inch) Disp..."
14,1,1479,3,"SAMSUNG Galaxy A05s (Light Green, 128 GB)",Mobiles,SAMSUNG,12990.0,"6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,1..."
18,1,1365,2,"vivo T2x 5G (Black Gladiator, 128 GB)",Mobiles,vivo,18999.0,"6 GB RAM | 128 GB ROM,16.71 cm (6.58 inch) Ful..."
24,1,58,2,"vivo T2x 5G (Black Gladiator, 128 GB)",Mobiles,vivo,18000.0,"8 GB RAM | 128 GB ROM,16.71 cm (6.58 inch) Ful..."
19,1,651,1,"SAMSUNG M15 5G (Celestrial Blue, 128 GB)",Mobiles,SAMSUNG,12099.0,"4 GB RAM | 128 GB ROM,16.51 cm (6.5 inch) Disp..."
47,1,1422,3,"vivo Y28 5G (Glitter Aqua, 128 GB)",Mobiles,vivo,18000.0,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
21,1,560,2,"vivo T3x 5G (Sapphire Blue, 128 GB)",Mobiles,vivo,15999.0,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
8,1,920,5,"SAMSUNG Galaxy F34 5G (Mystic Green, 128 GB)",Mobiles,SAMSUNG,24499.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
50,1,152,4,"SAMSUNG Galaxy A14 5G (Light Green, 128 GB)",Mobiles,SAMSUNG,9999.0,"4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
39,1,1312,3,"vivo Y28e (Breeze Green, 64 GB)",Mobiles,vivo,10290.0,"4 GB RAM | 64 GB ROM,16.66 cm (6.56 inch) Disp..."
40,1,595,2,"vivo Y18 (Space Black, 64 GB)",Mobiles,vivo,8499.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
49,1,644,3,"SAMSUNG Galaxy A15 5G (Blue, 128 GB)",Mobiles,SAMSUNG,16185.0,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
37,1,1377,3,"vivo T2 Pro 5G (Dune Gold, 128 GB)",Mobiles,vivo,22999.0,"8 GB RAM | 128 GB ROM,17.22 cm (6.78 inch) Ful..."
22,1,472,4,"SAMSUNG Galaxy A05 (Black, 64 GB)",Mobiles,SAMSUNG,9999.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17..."
10,1,230,1,"SAMSUNG Galaxy M15 5G (Stone Grey, 128 GB)",Mobiles,SAMSUNG,11895.0,"6 GB RAM | 128 GB ROM,16.51 cm (6.5 inch) Disp..."
16,1,585,3,"SAMSUNG Galaxy A15 5G (Blue Black, 128 GB)",Mobiles,SAMSUNG,16449.0,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
5,1,360,3,"SAMSUNG Galaxy A04s (Green, 64 GB)",Mobiles,SAMSUNG,15999.0,"4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) HD+ D..."
17,1,1436,1,"SAMSUNG Galaxy M34 5G (Waterfall Blue, 128 GB)",Mobiles,SAMSUNG,20392.0,"8 GB RAM | 128 GB ROM,16.51 cm (6.5 inch) Disp..."
13,1,910,4,"SAMSUNG Galaxy A04 (Green, 128 GB)",Mobiles,SAMSUNG,12999.0,"4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
26,1,1393,2,"SAMSUNG Galaxy F22 (Denim Black, 128 GB)",Mobiles,SAMSUNG,11990.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
48,1,287,1,"vivo Y17s (Forest Green, 64 GB)",Mobiles,vivo,9499.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
52,1,840,1,"SAMSUNG Galaxy M04 (Light Green, 128 GB)",Mobiles,SAMSUNG,11999.0,"4 GB RAM | 128 GB ROM | Expandable Upto 64 GB,..."
3,1,420,5,"SAMSUNG Galaxy F12 (Sea Green, 64 GB)",Mobiles,SAMSUNG,10499.0,"4 GB RAM | 64 GB ROM | Expandable Upto 512 GB,..."
27,1,80,1,"SAMSUNG Galaxy M55 5G (Light Green, 128 GB)",Mobiles,SAMSUNG,23499.0,"8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp..."

In [23]:
# 2 Amitesh ->mobiles(apple,oppo,samsung) | speakers(jbl) | television(SAMSUNG,LG)

In [24]:
mobile_data_2 = products_data_copy[
    (products_data_copy['Product Category'] == 'Mobiles') &
    (products_data_copy['Product Brand'].isin(['Apple', 'OPPO']))
]
print(mobile_data_2.shape)
mobile_data_2.head()

(148, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
0,1,"Apple iPhone 15 (Pink, 512 GB)",Mobiles,Apple,87999.0,"512 GB ROM,15.49 cm (6.1 inch) Super Retina XD..."
11,12,"Apple iPhone 16 (White, 128 GB)",Mobiles,Apple,79900.0,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD..."
24,25,"Apple iPhone 15 Pro Max (Natural Titanium, 512...",Mobiles,Apple,132999.0,"512 GB ROM,17.02 cm (6.7 inch) Super Retina XD..."
44,45,"OPPO Reno 12 5G (Astro Silver, 256 GB)",Mobiles,OPPO,32999.0,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1..."
47,48,"OPPO Reno11 5G (Rock Grey, 256 GB)",Mobiles,OPPO,29999.0,"8 GB RAM | 256 GB ROM | Expandable Upto 2 TB,1..."

In [25]:
speaker_brands['Product Brand'].unique()

array(['Landmark', 'boAt', 'Mivi', 'JBL', 'Portronics', 'SONY'],
      dtype=object)

In [26]:
speakers_data_2 = products_data_copy[
    (products_data_copy['Product Category'] == 'Speakers') &
    (products_data_copy['Product Brand'].isin(['JBL','SONY']))
]
print(speakers_data_2.shape)
speakers_data_2.head()

(5, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
405,406,"JBL Cinema SB240 2.1 with Remote, Dolby Digita...",Speakers,JBL,6998.0,"Power Output(RMS): 110 W,Power Source: AC Adap..."
823,824,SONY SA-D40 80 W Bluetooth Home Theatre,Speakers,SONY,8999.0,"Power Output(RMS): 80 W,Power Source: DC 18 V,..."
859,860,SONY HT-S20R 5.1ch Home Theatre with Dolby Dig...,Speakers,SONY,14988.0,"Power Output(RMS): 400 W,Power Source: AC Adap..."
962,963,SONY HT-S40R 5.1ch Dolby Audio Home Theatre wi...,Speakers,SONY,23988.0,"Power Output(RMS): 600 W,Power Source: AC Cord..."
1528,1529,"JBL Cinema SB270 2.1, Dolby digital, Wireless ...",Speakers,JBL,10998.0,"Power Output(RMS): 220 W,Power Source: AC Adap..."

In [27]:
television_brands = products_data_copy[products_data_copy['Product Category'] == 'Televisions']
print(television_brands['Product Brand'].unique())
print(television_brands.shape)
television_brands.head()

['SAMSUNG' 'LG' 'SONY' 'Mi']
(416, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
5,6,SAMSUNG 123 cm (49 inch) Full HD LED TV,Televisions,SAMSUNG,55099.0,"Full HD 1920 x 1080 Pixels,Launch Year: 2016,1..."
15,16,LG OLED A3 164 cm (65 inch) OLED Ultra HD (4K)...,Televisions,LG,159990.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
17,18,SONY Bravia 164 cm (65 inch) Ultra HD (4K) LED...,Televisions,SONY,175640.0,"Ultra HD (4K) 3840 x 2160 Pixels,Launch Year: ..."
20,21,SAMSUNG 123 cm (49 inch) Full HD LED Smart Tiz...,Televisions,SAMSUNG,75799.0,"Operating System: Tizen,Full HD 1920 x 1080 Pi..."
21,22,LG Nanocell 189 cm (75 inch) Ultra HD (4K) LED...,Televisions,LG,338599.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."

In [28]:
television_data_2 = products_data_copy[
    (products_data_copy['Product Category'] == 'Televisions') &
    (products_data_copy['Product Brand'].isin(['SAMSUNG','LG']))
]
print(television_data_2.shape)
television_data_2.sample(10)

(330, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
699,700,SAMSUNG 108 cm (43 inch) Ultra HD (4K) LED Sma...,Televisions,SAMSUNG,34490.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
1092,1093,SAMSUNG Crystal 4K Neo Series 138 cm (55 inch)...,Televisions,SAMSUNG,42990.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
199,200,SAMSUNG 80 cm (32 inch) HD Ready LED Smart Tiz...,Televisions,SAMSUNG,13490.0,"Operating System: Tizen,HD Ready 1366 x 768 Pi..."
498,499,SAMSUNG Series 4 80 cm (32 inch) HD Ready LED TV,Televisions,SAMSUNG,13633.0,"HD Ready 1366 x 768 Pixels,Launch Year: 2018,1..."
121,122,SAMSUNG The Frame 139.7 cm (55 inch) QLED Ultr...,Televisions,SAMSUNG,89990.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
1388,1389,SAMSUNG OLED 139.7 cm (55 inch) OLED Ultra HD ...,Televisions,SAMSUNG,154865.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
77,78,SAMSUNG BU8570UL 138 cm (55 inch) Ultra HD (4K...,Televisions,SAMSUNG,75000.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
32,33,SAMSUNG 5 108 cm (43 inch) Full HD LED Smart T...,Televisions,SAMSUNG,27670.0,"Operating System: Tizen,Full HD 1920 x 1080 Pi..."
636,637,LG QNED-80 189 cm (75 inch) Ultra HD (4K) QNED...,Televisions,LG,236199.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
125,126,SAMSUNG 176 cm (70 inch) Ultra HD (4K) LED Sma...,Televisions,SAMSUNG,89999.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."

In [29]:
interaction_df[interaction_df['user_id'] == 2].shape

(81, 3)

In [30]:
interaction_df = update_interaction_with_product_ids(
    interaction_df,  # Positional argument
    2,  # Positional argument for user_id
    mobile_data_2['product_id'].tolist(),  # Positional argument
    speakers_data_2['product_id'].tolist(),  # Positional argument
    television_data_2['product_id'].tolist()  # Positional argument
)

In [31]:
user_2_product_details = interaction_df[interaction_df['user_id'] == 2].merge(products_data_copy, on='product_id', how='left')
print(user_2_product_details['Product Category'].unique())
user_2_product_details.sample(25)

['Televisions' 'Mobiles' 'Speakers']

,user_id,product_id,rating,Product Name,Product Category,Product Brand,Product Price,Product Description
29,2,406,3,"JBL Cinema SB240 2.1 with Remote, Dolby Digita...",Speakers,JBL,6998.0,"Power Output(RMS): 110 W,Power Source: AC Adap..."
39,2,71,4,LG 32LQBPTA 80 cm (32 inch) HD Ready LED Smart...,Televisions,LG,14990.0,"Operating System: WebOS,HD Ready 1366 x 768 Pi..."
31,2,1235,1,LG Nanocell 139 cm (55 inch) Ultra HD (4K) LED...,Televisions,LG,104199.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
40,2,310,4,SAMSUNG QN95BAKL 163 cm (65 inch) QLED Ultra H...,Televisions,SAMSUNG,186929.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
44,2,732,1,"OPPO Reno11 5G (Wave Green, 128 GB)",Mobiles,OPPO,27999.0,"8 GB RAM | 128 GB ROM | Expandable Upto 2 TB,1..."
75,2,643,2,LG OLED C3 139 cm (55 inch) OLED Ultra HD (4K)...,Televisions,LG,125999.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
77,2,1143,2,LG 126 cm (50 inch) Ultra HD (4K) LED Smart We...,Televisions,LG,58899.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
54,2,980,3,"Apple iPhone 15 Plus (Black, 128 GB)",Mobiles,Apple,65999.0,"128 GB ROM,17.02 cm (6.7 inch) Super Retina XD..."
64,2,1520,4,"OPPO A3x 5G (Starlight White, 64 GB)",Mobiles,OPPO,12299.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
32,2,1061,3,SAMSUNG 163 cm (65 inch) Ultra HD (4K) LED Sma...,Televisions,SAMSUNG,69990.0,"Operating System: Tizen,Ultra HD (4K) 3840x216..."
15,2,35,4,LG UR7500 164 cm (65 inch) Ultra HD (4K) LED S...,Televisions,LG,64990.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
50,2,754,1,LG 164 cm (65 inch) Ultra HD (4K) LED Smart We...,Televisions,LG,102060.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
47,2,775,5,"OPPO Reno 12 5G (Sunset Peach, 256 GB)",Mobiles,OPPO,32999.0,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1..."
66,2,165,5,SAMSUNG 125 cm (50 inch) Ultra HD (4K) LED Sma...,Televisions,SAMSUNG,99599.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
48,2,191,4,SAMSUNG 163 cm (65 inch) QLED Ultra HD (4K) Sm...,Televisions,SAMSUNG,159990.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
49,2,1281,3,SAMSUNG New D Series Brighter Crystal 4K Visio...,Televisions,SAMSUNG,29990.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
73,2,76,1,OPPO K12x 5G with 45W SUPERVOOC Charger In-The...,Mobiles,OPPO,15999.0,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1..."
57,2,372,4,SAMSUNG AUE70 108 cm (43 inch) Ultra HD (4K) L...,Televisions,SAMSUNG,39990.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
2,2,56,1,SAMSUNG 80 cm (30 inch) HD Ready LED Smart Tiz...,Televisions,SAMSUNG,16499.0,"Operating System: Tizen,HD Ready 1366 x 768 Pi..."
43,2,784,1,LG OLED A2 164 cm (65 inch) OLED Ultra HD (4K)...,Televisions,LG,152199.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
22,2,842,3,"Apple iPhone 16 Pro (Black Titanium, 128 GB)",Mobiles,Apple,119900.0,"128 GB ROM,16.0 cm (6.3 inch) Super Retina XDR..."
41,2,768,4,SAMSUNG Series 6 163 cm (65 inch) Ultra HD (4K...,Televisions,SAMSUNG,241199.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
68,2,322,1,"OPPO Reno10 Pro 5G (Glossy Purple, 256 GB)",Mobiles,OPPO,37999.0,"12 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Ful..."
10,2,1009,3,LG 121.92 cm (48 inch) OLED Ultra HD (4K) Smar...,Televisions,LG,89990.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
79,2,399,1,SAMSUNG 138 cm (55 inch) Ultra HD (4K) LED Sma...,Televisions,SAMSUNG,59990.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."

In [32]:
# 3 Virat ->mobiles(Nokia,Google,POCO) | Kitchen Appliances(SAMSUNG,Panasonic) | television(SONY,Mi)

In [33]:
mobile_brands = products_data_copy[products_data_copy['Product Category'] == 'Mobiles']
mobile_brands['Product Brand'].unique()

array(['Apple', 'vivo', 'SAMSUNG', 'Nokia', 'Google', 'OnePlus', 'POCO',
       'OPPO', 'Samsung'], dtype=object)

In [34]:
mobile_data_3 = products_data_copy[
    (products_data_copy['Product Category'] == 'Mobiles') &
    (products_data_copy['Product Brand'].isin(['Nokia', 'Google', 'POCO']))
]
print(mobile_data_3.shape)
mobile_data_3.head()

(291, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
9,10,"Nokia 106 4G Keypad Mobile, Long-Lasting Batte...",Mobiles,Nokia,2235.0,"32 MB RAM | 32 MB ROM,4.5 cm (1.77 inch) Displ..."
13,14,"Google Pixel 7a (Snow, 128 GB)",Mobiles,Google,31999.0,"8 GB RAM | 128 GB ROM,15.49 cm (6.1 inch) Full..."
26,27,Nokia 215 4G,Mobiles,Nokia,2899.0,"64 MB RAM | 64 MB ROM,6.1 cm (2.4 inch) Displa..."
31,32,"Nokia C32 (Beach Pink, 64 GB)",Mobiles,Nokia,7899.0,"4 GB RAM | 64 GB ROM,16.55 cm (6.517 inch) Dis..."
33,34,"POCO C65 (Matte Black, 256 GB)",Mobiles,POCO,9499.0,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1..."

In [35]:
kitchen_appli_brands = products_data_copy[products_data_copy['Product Category'] == 'Kitchen Appliances']
kitchen_appli_brands['Product Brand'].unique()

array(['LG', 'IFB', 'SAMSUNG', 'Panasonic'], dtype=object)

In [36]:
kitchen_appli_data_3 = products_data_copy[
    (products_data_copy['Product Category'] == 'Kitchen Appliances') &
    (products_data_copy['Product Brand'].isin(['SAMSUNG', 'Panasonic']))
]
print(kitchen_appli_data_3.shape)
kitchen_appli_data_3.head()

(46, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
83,84,SAMSUNG 21 L Convection Microwave Oven,Kitchen Appliances,SAMSUNG,12129.0,"Control Type: Touch Key Pad (Membrane),Child L..."
100,101,SAMSUNG 32 L Convection Microwave Oven,Kitchen Appliances,SAMSUNG,21800.0,"Control Type: Jog Dial, Feather Touch,1 year o..."
143,144,Panasonic 30 L Convection Microwave Oven,Kitchen Appliances,Panasonic,15490.0,"Control Type: Jog Dial,Child Lock Present,1 Ye..."
212,213,SAMSUNG 28 L Convection Microwave Oven,Kitchen Appliances,SAMSUNG,18522.0,Control Type: Touch Key Pad (Membrane)
232,233,Panasonic 23 L Convection & Grill Microwave Oven,Kitchen Appliances,Panasonic,12290.0,Control Type: Touch Key Pad (Membrane)

In [37]:
television_data_3 = products_data_copy[
    (products_data_copy['Product Category'] == 'Televisions') &
    (products_data_copy['Product Brand'].isin(['SONY','Mi']))
]
print(television_data_3.shape)
television_data_3.sample(10)

(86, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
503,504,SONY Bravia 2 125.7 cm (50 inch) Ultra HD (4K)...,Televisions,SONY,59840.0,"Operating System: Google TV,Ultra HD (4K) 3840..."
745,746,SONY Bravia 163.9 cm (65 inch) Ultra HD (4K) L...,Televisions,SONY,94990.0,"Operating System: Android,Ultra HD (4K) 3840 x..."
1325,1326,Mi by Xiaomi X Series 108 cm (43 inch) Ultra H...,Televisions,Mi,22999.0,"Operating System: Google TV,Ultra HD (4K) 3840..."
1389,1390,SONY 80 cm (32 inch) HD Ready LED Smart Google...,Televisions,SONY,25999.0,"Operating System: Google TV,HD Ready 1366 x 76..."
760,761,SONY Bravia X64L 108 cm (43 inch) Ultra HD (4K...,Televisions,SONY,38990.0,"Operating System: Google TV,Ultra HD (4K) 3840..."
345,346,Mi 4A Horizon Edition 100 cm (40 inch) Full HD...,Televisions,Mi,29999.0,"Operating System: Android,Full HD 1920 x 1080 ..."
776,777,Mi by Xiaomi X Pro QLED 138 cm (55 inch) QLED ...,Televisions,Mi,49999.0,"Operating System: Google TV,Ultra HD (4K) 3840..."
245,246,SONY Bravia 80 cm (32 inch) HD Ready LED Smart...,Televisions,SONY,32999.0,"Operating System: Linux based,HD Ready 1366 x ..."
948,949,SONY Bravia 2 125.7 cm (50 inch) Ultra HD (4K)...,Televisions,SONY,62690.0,"Operating System: Google TV,Ultra HD (4K) 3840..."
1131,1132,SONY Bravia 138.8 cm (55 inch) OLED Ultra HD (...,Televisions,SONY,156900.0,"Operating System: Google TV,Ultra HD (4K) 3840..."

In [38]:
interaction_df = update_interaction_with_product_ids(
    interaction_df,  # Positional argument
    3,  # Positional argument for user_id
    mobile_data_3['product_id'].tolist(),  # Positional argument
    kitchen_appli_data_3['product_id'].tolist(),  # Positional argument
    television_data_3['product_id'].tolist()  # Positional argument
)

In [39]:
user_3_product_details = interaction_df[interaction_df['user_id'] == 3].merge(products_data_copy, on='product_id', how='left')
print(user_3_product_details['Product Category'].unique())
user_3_product_details.sample(25)

['Kitchen Appliances' 'Mobiles' 'Televisions']

,user_id,product_id,rating,Product Name,Product Category,Product Brand,Product Price,Product Description
44,3,857,3,Nokia 2660 Flip 4G Volte Red keypad Mobile wit...,Mobiles,Nokia,4698.0,"0.046875 GB RAM | 0.125 GB ROM,7.11 cm (2.8 in..."
4,3,991,5,"Nokia 3.4 (Fjord BLUE, 64 GB)",Mobiles,Nokia,13999.0,"4 GB RAM | 64 GB ROM | Expandable Upto 512 GB,..."
40,3,1268,4,"POCO F5 5G (Carbon Black, 256 GB)",Mobiles,POCO,23799.0,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu..."
42,3,1478,1,SONY Bravia 2 125.7 cm (50 inch) Ultra HD (4K)...,Televisions,SONY,53990.0,"Operating System: Google TV,Ultra HD (4K) 3840..."
17,3,14,5,"Google Pixel 7a (Snow, 128 GB)",Mobiles,Google,31999.0,"8 GB RAM | 128 GB ROM,15.49 cm (6.1 inch) Full..."
38,3,105,3,"POCO M3 (Power Black, 64 GB)",Mobiles,POCO,12999.0,"6 GB RAM | 64 GB ROM | Expandable Upto 512 GB,..."
39,3,223,1,SONY Bravia 126 cm (50 Inch) Ultra HD (4K) LED...,Televisions,SONY,69990.0,"Operating System: Google TV,Ultra HD (4K) 3840..."
11,3,640,5,Nokia Asha 206,Mobiles,Nokia,4499.0,"32 MB RAM | 64 MB ROM | Expandable Upto 32 GB,..."
45,3,1368,1,Nokia 2660 Flip 4G Volte Black keypad Mobile w...,Mobiles,Nokia,5289.0,"0.046875 GB RAM | 0.125 GB ROM,7.11 cm (2.8 in..."
31,3,1168,4,"Nokia 5710 Phone with Wireless Earbuds, MP3 Pl...",Mobiles,Nokia,4599.0,"0.046875 GB RAM | 0.125 GB ROM,6.1 cm (2.4 inc..."
14,3,763,3,"POCO M4 Pro (Yellow, 128 GB)",Mobiles,POCO,11990.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
35,3,1051,1,SAMSUNG 21 L Convection Microwave Oven,Kitchen Appliances,SAMSUNG,12044.0,"Control Type: Touch Key Pad (Membrane),Child L..."
13,3,304,3,Nokia 105,Mobiles,Nokia,1220.0,"32 MB RAM | 32 MB ROM | Expandable Upto 32 MB,..."
32,3,204,3,"POCO M6 Plus 5G (Graphite Black, 128 GB)",Mobiles,POCO,11499.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
49,3,32,3,"Nokia C32 (Beach Pink, 64 GB)",Mobiles,Nokia,7899.0,"4 GB RAM | 64 GB ROM,16.55 cm (6.517 inch) Dis..."
1,3,656,3,"POCO C61 (Ethereal Blue, 64 GB)",Mobiles,POCO,6299.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17..."
34,3,690,2,"POCO F4 5G (Night Black, 256 GB)",Mobiles,POCO,21950.0,"12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Fu..."
48,3,264,1,Panasonic 20 L Convection Microwave Oven,Kitchen Appliances,Panasonic,11500.0,"Control Type: Touch Key Pad (Membrane),Child L..."
24,3,1241,1,Nokia 301,Mobiles,Nokia,4999.0,"64 MB RAM | 64 MB ROM | Expandable Upto 32 GB,..."
8,3,802,2,"Nokia C32 (Breezy Mint, 128 GB)",Mobiles,Nokia,7998.0,"6 GB RAM | 128 GB ROM,16.55 cm (6.517 inch) Di..."
33,3,1016,4,SONY Bravia 163.9 cm (65 inch) Ultra HD (4K) L...,Televisions,SONY,79990.0,"Operating System: Google TV,Ultra HD (4K) 3840..."
23,3,740,3,Mi 5A 100 cm (40 inch) Full HD LED Smart Andro...,Televisions,Mi,20990.0,"Operating System: Android,Full HD 1920 x 1080 ..."
3,3,623,3,"Nokia 105 Single SIM, Keypad Mobile Phone with...",Mobiles,Nokia,1291.0,"32 MB RAM | 32 MB ROM,4.5 cm (1.77 inch) Displ..."
46,3,696,3,"Google Pixel 8a (Aloe, 128 GB)",Mobiles,Google,43999.0,"8 GB RAM | 128 GB ROM,15.49 cm (6.1 inch) Full..."
29,3,434,3,"Google Pixel 9 Pro XL (Porcelain, 256 GB)",Mobiles,Google,124999.0,"16 GB RAM | 256 GB ROM,17.27 cm (6.8 inch) Dis..."

In [40]:
# 4 Roman ->mobiles(OnePlus,Google,POCO) | Kitchen Appliances(IFB,LG) | speaker(Landmark,Mivi,Portronics)

In [41]:
products_data_copy['Product Category'].unique()

array(['Mobiles', 'Televisions', 'Kitchen Appliances', 'Speakers'],
      dtype=object)

In [42]:
mobile_data_4 = products_data_copy[
    (products_data_copy['Product Category'] == 'Mobiles') &
    (products_data_copy['Product Brand'].isin(['OnePlus', 'Google', 'POCO'])) &
    (products_data_copy['Product Price'] < 30000)
]
print(mobile_data_4.shape)
mobile_data_4.head()

(194, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
33,34,"POCO C65 (Matte Black, 256 GB)",Mobiles,POCO,9499.0,"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,1..."
35,36,"OnePlus 9 5G (Astral Black, 128 GB)",Mobiles,OnePlus,27899.0,"8 GB RAM | 128 GB ROM,16.64 cm (6.55 inch) Dis..."
37,38,"POCO X2 (Matrix Purple, 64 GB)",Mobiles,POCO,14999.0,"6 GB RAM | 64 GB ROM | Expandable Upto 512 GB,..."
45,46,"OnePlus N20 SE (CELESTIAL BLACK, 128 GB)",Mobiles,OnePlus,10925.0,"4 GB RAM | 128 GB ROM,16.66 cm (6.56 inch) Dis..."
59,60,"POCO X6 Pro 5G (Yellow, 256 GB)",Mobiles,POCO,20999.0,"8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Dis..."

In [43]:
kitchen_appli_data_4 = products_data_copy[
    (products_data_copy['Product Category'] == 'Kitchen Appliances') &
    (products_data_copy['Product Brand'].isin(['IFB', 'LG']))
]
print(kitchen_appli_data_4.shape)
kitchen_appli_data_4.head()

(55, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
18,19,LG 28 L Health Plus Menu and Stainless Steel C...,Kitchen Appliances,LG,12990.0,"Control Type: Touch Key Pad (Membrane),Manufac..."
25,26,LG 28 L Healthy Heart and 360 Motorised Rotiss...,Kitchen Appliances,LG,17470.0,"Control Type: Tact (Buttons),Manufacturer Warr..."
43,44,IFB 20 L Metallic silver Convection Microwave ...,Kitchen Appliances,IFB,9990.0,"Control Type: Touch Key Pad (Membrane),Child L..."
51,52,LG 28 L Diet Fry and 360 Motorised Rotisserie ...,Kitchen Appliances,LG,14499.0,"Control Type: Tact (Buttons), Jog Dial,Child L..."
81,82,LG 32 L Convection Microwave Oven,Kitchen Appliances,LG,23029.0,"Control Type: Feather Touch,Child Lock Present..."

In [44]:
speakers_data_4 = products_data_copy[
    (products_data_copy['Product Category'] == 'Speakers') &
    (products_data_copy['Product Brand'].isin(['Landmark','Mivi', 'Portronics']))
]
print(speakers_data_4.shape)
speakers_data_4.head()

(23, 6)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
41,42,Landmark LM BS117 Portable Home TV Soundbar wi...,Speakers,Landmark,899.0,"Power Output(RMS): 20 W,Battery life: 6 hr | C..."
84,85,"Mivi Fort S16 with 2 full range drivers, Made ...",Speakers,Mivi,1099.0,"Power Output(RMS): 16 W,Power Source: 5V DC Ty..."
159,160,Landmark LM BS117 Portable Home TV Soundbar wi...,Speakers,Landmark,899.0,"Power Output(RMS): 20 W,Battery life: 6 hr | C..."
239,240,Landmark LM BS117 Portable Home TV Soundbar wi...,Speakers,Landmark,899.0,"Power Output(RMS): 20 W,Battery life: 6 hr | C..."
319,320,Landmark BT-1024 Grey Wood ROAR Sound Bar High...,Speakers,Landmark,1616.0,"Power Output(RMS): 20 W,Power Source: Micro US..."

In [45]:
interaction_df = update_interaction_with_product_ids(
    interaction_df,  # Positional argument
    4,  # Positional argument for user_id
    mobile_data_4['product_id'].tolist(),  # Positional argument
    kitchen_appli_data_4['product_id'].tolist(),  # Positional argument
    speakers_data_4['product_id'].tolist()  # Positional argument
)

In [46]:
user_4_product_details = interaction_df[interaction_df['user_id'] == 4].merge(products_data_copy, on='product_id', how='left')
print(user_4_product_details['Product Category'].unique())
user_4_product_details.sample(25)

['Mobiles' 'Kitchen Appliances' 'Speakers']

,user_id,product_id,rating,Product Name,Product Category,Product Brand,Product Price,Product Description
51,4,1069,4,"POCO X6 5G (Mirror Black, 512 GB)",Mobiles,POCO,18999.0,"12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Di..."
26,4,764,4,Landmark BT-1024 Brown Wood ROAR Sound Bar Hig...,Speakers,Landmark,1619.0,"Power Output(RMS): 20 W,Power Source: Micro US..."
38,4,446,3,"POCO C31 (Royal Blue, 32 GB)",Mobiles,POCO,8499.0,"3 GB RAM | 32 GB ROM | Expandable Upto 512 GB,..."
29,4,566,5,"OnePlus Nord CE3 5G (Grey Shimmer, 128 GB)",Mobiles,OnePlus,19590.0,"8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp..."
19,4,763,1,"POCO M4 Pro (Yellow, 128 GB)",Mobiles,POCO,11990.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
65,4,199,3,"POCO M6 Pro 5G (Power Black, 128 GB)",Mobiles,POCO,11999.0,"4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
44,4,1287,4,"POCO M5 (Power Black, 64 GB)",Mobiles,POCO,8799.0,"4 GB RAM | 64 GB ROM | Expandable Upto 512 GB,..."
62,4,373,5,IFB 23 L Convection Microwave Oven,Kitchen Appliances,IFB,13100.0,"Control Type: Feather Touch,Child Lock Present..."
5,4,459,2,"POCO C31 (Royal Blue, 64 GB)",Mobiles,POCO,9499.0,"4 GB RAM | 64 GB ROM | Expandable Upto 512 GB,..."
39,4,115,2,"POCO C65 (Matte Black, 128 GB)",Mobiles,POCO,7799.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
49,4,107,3,"OnePlus Nord CE4 lite 5G (ULTRA ORANGE, 128 GB)",Mobiles,OnePlus,17679.0,"8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Dis..."
63,4,377,4,"Mivi Fort S38 With Sub woofer, 38W, BT v5.3, S...",Speakers,Mivi,2099.0,"Power Output(RMS): 38 W,Bluetooth Version: 5.1..."
3,4,580,2,"POCO C3 (Arctic Blue, 32 GB)",Mobiles,POCO,8290.0,"3 GB RAM | 32 GB ROM | Expandable Upto 512 GB,..."
32,4,1135,1,"POCO C61 (Mystical Green, 128 GB)",Mobiles,POCO,8499.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
27,4,600,3,IFB 25 L Solo Microwave Oven,Kitchen Appliances,IFB,7490.0,"Control Type: Mechanical Knob, Tact (Buttons),..."
43,4,331,4,"POCO M6 5G (Galactic Black, 128 GB)",Mobiles,POCO,9799.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
23,4,1525,3,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",Mobiles,OnePlus,15605.0,"8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch) Dis..."
60,4,1090,2,"POCO C51 (Power Black, 64 GB)",Mobiles,POCO,8499.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
50,4,1021,1,"Mivi Fort S100 with 2 in-built subwoofers, Mad...",Speakers,Mivi,4499.0,"Power Output(RMS): 100 W,Power Source: DC Adap..."
2,4,517,1,"POCO M6 5G (Orion Blue, 128 GB)",Mobiles,POCO,9799.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
13,4,641,2,"POCO F6 5G (Black, 256 GB)",Mobiles,POCO,23999.0,"8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Dis..."
67,4,923,2,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)",Mobiles,OnePlus,15827.0,"8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch) Dis..."
31,4,1163,1,"POCO M5 (Icy Blue, 64 GB)",Mobiles,POCO,8799.0,"4 GB RAM | 64 GB ROM | Expandable Upto 512 GB,..."
6,4,1366,3,"OnePlus Nord 3 5G (Tempest Gray, 128 GB)",Mobiles,OnePlus,22388.0,"8 GB RAM | 128 GB ROM,17.12 cm (6.74 inch) Ful..."
25,4,100,2,"POCO X6 Pro 5G (Spectre Black, 256 GB)",Mobiles,POCO,20999.0,"8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Dis..."

In [47]:
print(interaction_df.shape)
interaction_df.sample(25)

(256, 3)

     user_id  product_id  rating
160        2         191       4
133        2         297       3
135        1         231       3
196        1        1312       3
100        1         560       2
242        1         287       1
87         1        1436       1
19         4         459       2
187        2        1522       5
128        1         826       5
35         3        1534       3
55         1         313       2
111        1          58       2
49         1         542       4
250        2        1448       2
12         4         517       1
123        2         627       3
54         3        1380       3
96         1        1533       1
47         3         802       2
122        2          16       2
186        2         839       4
119        3         125       3
194        2         695       2
75         2         911       5

In [48]:
interaction_df.to_csv('ecomprod_interaction_df.csv', index=False)

In [49]:
# 1 mohit ->mobiles(vivo,samsung,<25000) | speakers(jbl,sony,boAt) 
# 2 Amitesh ->mobiles(apple,oppo,samsung) | speakers(jbl) | television(SAMSUNG,LG)
# 3 Virat ->mobiles(Nokia,Google,POCO) | Kitchen Appliances(SAMSUNG,Panasonic) | television(SONY,Mi)
# 4 Roman ->mobiles(OnePlus,Google,POCO) | Kitchen Appliances(IFB,LG) | speaker(Landmark,Mivi,Portronics)

interaction_df.merge(products_data_copy, on='product_id', how='left').sample(20)

,user_id,product_id,rating,Product Name,Product Category,Product Brand,Product Price,Product Description
136,2,1010,2,LG G3 164 cm (65 inch) OLED Ultra HD (4K) Smar...,Televisions,LG,224990.0,"Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
105,1,472,4,"SAMSUNG Galaxy A05 (Black, 64 GB)",Mobiles,SAMSUNG,9999.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,17..."
30,1,947,4,"SAMSUNG Galaxy F15 5G (Groovy Violet, 128 GB)",Mobiles,SAMSUNG,13499.0,"4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
45,4,193,1,"POCO M6 Pro 5G (Forest Green, 128 GB)",Mobiles,POCO,12999.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
94,1,651,1,"SAMSUNG M15 5G (Celestrial Blue, 128 GB)",Mobiles,SAMSUNG,12099.0,"4 GB RAM | 128 GB ROM,16.51 cm (6.5 inch) Disp..."
195,3,105,3,"POCO M3 (Power Black, 64 GB)",Mobiles,POCO,12999.0,"6 GB RAM | 64 GB ROM | Expandable Upto 512 GB,..."
149,2,732,1,"OPPO Reno11 5G (Wave Green, 128 GB)",Mobiles,OPPO,27999.0,"8 GB RAM | 128 GB ROM | Expandable Upto 2 TB,1..."
97,3,445,4,"POCO X4 Pro 5G (Laser Blue, 128 GB)",Mobiles,POCO,21999.0,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
131,4,532,4,"POCO C50 (Royal Blue, 32 GB)",Mobiles,POCO,6990.0,"2 GB RAM | 32 GB ROM | Expandable Upto 512 GB,..."
205,4,579,4,"POCO F4 5G (Nebula Green, 128 GB)",Mobiles,POCO,18990.0,"8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Ful..."
206,1,595,2,"vivo Y18 (Space Black, 64 GB)",Mobiles,vivo,8499.0,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
139,2,310,4,SAMSUNG QN95BAKL 163 cm (65 inch) QLED Ultra H...,Televisions,SAMSUNG,186929.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
2,2,122,5,SAMSUNG The Frame 139.7 cm (55 inch) QLED Ultr...,Televisions,SAMSUNG,89990.0,"Operating System: Tizen,Ultra HD (4K) 3840 x 2..."
228,3,1368,1,Nokia 2660 Flip 4G Volte Black keypad Mobile w...,Mobiles,Nokia,5289.0,"0.046875 GB RAM | 0.125 GB ROM,7.11 cm (2.8 in..."
189,4,288,4,"POCO F4 5G (Nebula Green, 128 GB)",Mobiles,POCO,16599.0,"6 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Ful..."
196,1,1312,3,"vivo Y28e (Breeze Green, 64 GB)",Mobiles,vivo,10290.0,"4 GB RAM | 64 GB ROM,16.66 cm (6.56 inch) Disp..."
95,3,115,2,"POCO C65 (Matte Black, 128 GB)",Mobiles,POCO,7799.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
8,1,518,5,"SAMSUNG Galaxy A54 5G (Awesome Graphite, 128 GB)",Mobiles,SAMSUNG,24906.0,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
70,4,475,5,"OnePlus Nord CE4 (Dark Chrome, 256 GB)",Mobiles,OnePlus,24199.0,"8 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Disp..."
141,4,500,3,"POCO C65 (Pastel Green, 128 GB)",Mobiles,POCO,7799.0,"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."

# Data Cleaning & Preprocessing

In [50]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [51]:
users_data = pd.read_csv('users.csv')
users_interest_data = pd.read_csv('ecomprod_interaction_df.csv')

In [52]:
users_data.head()

   user_id user_name                email
0        1     Mohit    mohit07@gmail.com
1        2   Amitesh  amitesh03@gmail.com
2        3     Virat    virat18@gmail.com
3        4     Roman    roman01@gmail.com

In [53]:
users_interest_data.head()

   user_id  product_id  rating
0        4         421       1
1        3         493       2
2        2         122       5
3        2        1260       3
4        1        1205       5

In [54]:
user_interest_counts = users_interest_data.groupby('user_id').size()
print(user_interest_counts.describe())

count     4.000000
mean     64.000000
std      14.023789
min      52.000000
25%      52.750000
50%      61.500000
75%      72.750000
max      81.000000
dtype: float64

In [55]:
products_data.sample(20)

,product_id,Product Name,Product Category,Product Brand,Product Price,Product Description
815,816,"Google Pixel 9 Pro XL (Obsidian, 256 GB)",Mobiles,Google,"₹1,24,999","16 GB RAM | 256 GB ROM,17.27 cm (6.8 inch) Dis..."
1251,1252,"vivo V40e 5G (Royal Bronze, 128 GB)",Mobiles,vivo,"₹28,999","8 GB RAM | 128 GB ROM,17.2 cm (6.77 inch) Disp..."
234,235,"vivo Y28e (?Vintage Red, 64 MB)",Mobiles,vivo,"₹11,450","4 GB RAM | 64 MB ROM,16.66 cm (6.56 inch) Disp..."
1204,1205,"vivo T2x 5G (Black Gladiator, 128 GB)",Mobiles,vivo,"₹17,999","4 GB RAM | 128 GB ROM,16.71 cm (6.58 inch) Ful..."
1114,1115,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)",Mobiles,OnePlus,"₹24,988","8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Disp..."
1520,1521,"vivo V25 5G (Sunrise Gold, 128 GB)",Mobiles,vivo,"₹27,999","8 GB RAM | 128 GB ROM,16.36 cm (6.44 inch) Ful..."
1084,1085,"POCO M2 Pro (Green and Greener, 128 GB)",Mobiles,POCO,"₹19,999",6 GB RAM | 128 GB ROM | Expandable Upto 512 GB...
1131,1132,SONY Bravia 138.8 cm (55 inch) OLED Ultra HD (...,Televisions,SONY,"₹1,56,900","Operating System: Google TV,Ultra HD (4K) 3840..."
469,470,"POCO X3 Pro (Golden Bronze, 128 GB)",Mobiles,POCO,"₹18,890","6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
109,110,"vivo T3 Lite 5G (Majestic Black, 128 GB)",Mobiles,vivo,"₹10,499","4 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
228,229,"POCO F6 5G (Titanium, 256 GB)",Mobiles,POCO,"₹23,999","8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Dis..."
1000,1001,"SAMSUNG Galaxy A10 (Black, 32 GB)",Mobiles,SAMSUNG,"₹8,700","2 GB RAM | 32 GB ROM | Expandable Upto 512 GB,..."
827,828,"vivo V27 Pro 5G (Magic Blue, 128 GB)",Mobiles,vivo,"₹37,999","8 GB RAM | 128 GB ROM,17.22 cm (6.78 inch) Ful..."
628,629,LG 32 L Diet Fry and 360 Motorised Rotisserie ...,Kitchen Appliances,LG,"₹17,590","Control Type: Jog Dial, Tact (Buttons),Manufac..."
744,745,LG 164 cm (65 inch) Ultra HD (4K) LED Smart We...,Televisions,LG,"₹1,11,990","Operating System: WebOS,Ultra HD (4K) 3840 x 2..."
511,512,LG 109 cm (43 inch) Ultra HD (4K) LED Smart We...,Televisions,LG,"₹35,500","Operating System: WebOS,Ultra HD (4K) 3,840 x ..."
641,642,"POCO X6 Neo 5G (Horizon Blue, 128 GB)",Mobiles,POCO,"₹12,999","8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
916,917,"OnePlus Nord 2T 5G (Jade Fog, 256 GB)",Mobiles,OnePlus,"₹29,999","12 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Dis..."
684,685,IFB 23 L Convection Microwave Oven,Kitchen Appliances,IFB,"₹10,790","Control Type: Touch Key Pad (Membrane),Child L..."
55,56,SAMSUNG 80 cm (30 inch) HD Ready LED Smart Tiz...,Televisions,SAMSUNG,"₹16,499","Operating System: Tizen,HD Ready 1366 x 768 Pi..."

In [56]:
products_data.shape

(1541, 6)

In [57]:
products_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1541 entries, 0 to 1540
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1541 non-null   int64
 1   Product Name         1541 non-null   object
 2   Product Category     1541 non-null   object
 3   Product Brand        1541 non-null   object
 4   Product Price        1541 non-null   object
 5   Product Description  1541 non-null   object
dtypes: int64(1), object(5)
memory usage: 72.4+ KB

In [58]:
products_data.isnull().mean()*100

product_id             0.0
Product Name           0.0
Product Category       0.0
Product Brand          0.0
Product Price          0.0
Product Description    0.0
dtype: float64

In [59]:
products_data.duplicated().sum()

0

In [60]:
# Renaming columns using a dictionary
products_data = products_data.rename(columns={
    'Product Name': 'product_name',
    'Product Category': 'product_category',
    'Product Brand': 'product_brand',
    'Product Price': 'product_price',
    'Product Description': 'product_description',  
})

In [61]:
products_data.head()

,product_id,product_name,product_category,product_brand,product_price,product_description
0,1,"Apple iPhone 15 (Pink, 512 GB)",Mobiles,Apple,"₹87,999","512 GB ROM,15.49 cm (6.1 inch) Super Retina XD..."
1,2,"vivo Y22 (Starlit Blue, 64 GB)",Mobiles,vivo,"₹14,499","4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
2,3,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",Mobiles,SAMSUNG,"₹1,08,999","12 GB RAM | 256 GB ROM,17.27 cm (6.8 inch) Qua..."
3,4,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",Mobiles,SAMSUNG,"₹24,790","8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
4,5,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",Mobiles,SAMSUNG,"₹8,999","4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) HD+ D..."

In [62]:
products_data['product_price'] = products_data['product_price'].replace({'Not Available': np.nan})

In [63]:
products_data['product_price'] = (
    products_data['product_price']
    .replace('[₹,]', '', regex=True)
)

In [64]:
products_data.head()

,product_id,product_name,product_category,product_brand,product_price,product_description
0,1,"Apple iPhone 15 (Pink, 512 GB)",Mobiles,Apple,87999,"512 GB ROM,15.49 cm (6.1 inch) Super Retina XD..."
1,2,"vivo Y22 (Starlit Blue, 64 GB)",Mobiles,vivo,14499,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16..."
2,3,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",Mobiles,SAMSUNG,108999,"12 GB RAM | 256 GB ROM,17.27 cm (6.8 inch) Qua..."
3,4,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",Mobiles,SAMSUNG,24790,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1..."
4,5,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",Mobiles,SAMSUNG,8999,"4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) HD+ D..."

In [65]:
products_data.iloc[3].product_name

'SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)'

In [66]:
products_data.iloc[3].product_description

'8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.26 cm (6.4 inch) Full HD+ Display,50MP + 12MP + 5MP | 32MP Front Camera,5000 mAh Battery,Exynos 1380, Octa Core Processor,1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories'

In [67]:
products_data['tags'] = products_data['product_category'] + ' ' + products_data['product_brand'] + ' ' + products_data['product_description']

In [68]:
products_data.head()

,product_id,product_name,product_category,product_brand,product_price,product_description,tags
0,1,"Apple iPhone 15 (Pink, 512 GB)",Mobiles,Apple,87999,"512 GB ROM,15.49 cm (6.1 inch) Super Retina XD...","Mobiles Apple 512 GB ROM,15.49 cm (6.1 inch) S..."
1,2,"vivo Y22 (Starlit Blue, 64 GB)",Mobiles,vivo,14499,"4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,16...",Mobiles vivo 4 GB RAM | 64 GB ROM | Expandable...
2,3,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",Mobiles,SAMSUNG,108999,"12 GB RAM | 256 GB ROM,17.27 cm (6.8 inch) Qua...","Mobiles SAMSUNG 12 GB RAM | 256 GB ROM,17.27 c..."
3,4,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",Mobiles,SAMSUNG,24790,"8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,1...",Mobiles SAMSUNG 8 GB RAM | 128 GB ROM | Expand...
4,5,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",Mobiles,SAMSUNG,8999,"4 GB RAM | 64 GB ROM,16.51 cm (6.5 inch) HD+ D...","Mobiles SAMSUNG 4 GB RAM | 64 GB ROM,16.51 cm ..."

In [69]:
products_data.to_csv('ecom_products_data.csv', index=False)

In [70]:
ecom_data = products_data[['product_id', 'product_price', 'product_name', 'tags']]

In [71]:
ecom_data.head()

,product_id,product_price,product_name,tags
0,1,87999,"Apple iPhone 15 (Pink, 512 GB)","Mobiles Apple 512 GB ROM,15.49 cm (6.1 inch) S..."
1,2,14499,"vivo Y22 (Starlit Blue, 64 GB)",Mobiles vivo 4 GB RAM | 64 GB ROM | Expandable...
2,3,108999,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...","Mobiles SAMSUNG 12 GB RAM | 256 GB ROM,17.27 c..."
3,4,24790,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",Mobiles SAMSUNG 8 GB RAM | 128 GB ROM | Expand...
4,5,8999,"SAMSUNG Galaxy M04 (Light Green, 64 GB)","Mobiles SAMSUNG 4 GB RAM | 64 GB ROM,16.51 cm ..."

In [72]:
# nltk.download('stopwords')
# nltk.download('wordnet')

In [73]:
def clean_product_description(description):
    # Convert to lowercase
    description = description.lower()
    
    # Remove special characters, punctuation, and extra spaces
    description = re.sub(r'[^a-z0-9.\s]', ' ', description)
    
    # Tokenize and remove stop words
    stop_words = set(stopwords.words('english'))
    tokens = description.split()
    filtered_tokens = [word for word in tokens if word not in stop_words]
    
    # Lemmatize the words to reduce them to their base form
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]
    
    # Join the cleaned tokens back into a single string
    cleaned_description = ' '.join(lemmatized_tokens)
    
    return cleaned_description

In [74]:
ecom_data.iloc[3].tags

'Mobiles SAMSUNG 8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,16.26 cm (6.4 inch) Full HD+ Display,50MP + 12MP + 5MP | 32MP Front Camera,5000 mAh Battery,Exynos 1380, Octa Core Processor,1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories'

In [75]:
cleaned_description = clean_product_description(ecom_data.iloc[3].tags)
print(cleaned_description)

mobile samsung 8 gb ram 128 gb rom expandable upto 1 tb 16.26 cm 6.4 inch full hd display 50mp 12mp 5mp 32mp front camera 5000 mah battery exynos 1380 octa core processor 1 year manufacturer warranty device 6 month manufacturer warranty box accessory

In [76]:
ecom_data['tags'] = ecom_data['tags'].apply(clean_product_description)

/tmp/ipykernel_11416/1063237155.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ecom_data['tags'] = ecom_data['tags'].apply(clean_product_description)

In [77]:
ecom_data.head()

,product_id,product_price,product_name,tags
0,1,87999,"Apple iPhone 15 (Pink, 512 GB)",mobile apple 512 gb rom 15.49 cm 6.1 inch supe...
1,2,14499,"vivo Y22 (Starlit Blue, 64 GB)",mobile vivo 4 gb ram 64 gb rom expandable upto...
2,3,108999,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",mobile samsung 12 gb ram 256 gb rom 17.27 cm 6...
3,4,24790,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",mobile samsung 8 gb ram 128 gb rom expandable ...
4,5,8999,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",mobile samsung 4 gb ram 64 gb rom 16.51 cm 6.5...

In [78]:
ecom_data['tags'].iloc[0]

'mobile apple 512 gb rom 15.49 cm 6.1 inch super retina xdr display 48mp 12mp 12mp front camera a16 bionic chip 6 core processor processor 1 year warranty phone 6 month warranty box accessory'

In [79]:
ecom_data['product_name'].iloc[0]

'Apple iPhone 15 (Pink, 512 GB)'

In [80]:
# def product_name_clean(product_name):
#     cleaned_name = re.sub(r'\(.*?\)', '', product_name).strip()
#     cleaned_name = cleaned_name.lower()
#     return cleaned_name

In [81]:
# ecom_data['product_name'] = ecom_data['product_name'].apply(product_name_clean)

In [82]:
ecom_data.head()

,product_id,product_price,product_name,tags
0,1,87999,"Apple iPhone 15 (Pink, 512 GB)",mobile apple 512 gb rom 15.49 cm 6.1 inch supe...
1,2,14499,"vivo Y22 (Starlit Blue, 64 GB)",mobile vivo 4 gb ram 64 gb rom expandable upto...
2,3,108999,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",mobile samsung 12 gb ram 256 gb rom 17.27 cm 6...
3,4,24790,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",mobile samsung 8 gb ram 128 gb rom expandable ...
4,5,8999,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",mobile samsung 4 gb ram 64 gb rom 16.51 cm 6.5...

In [83]:
ecom_data.shape

(1541, 4)

In [84]:
ecom_data['tags'][0]

'mobile apple 512 gb rom 15.49 cm 6.1 inch super retina xdr display 48mp 12mp 12mp front camera a16 bionic chip 6 core processor processor 1 year warranty phone 6 month warranty box accessory'

In [85]:
ecom_data['product_price'] = pd.to_numeric(ecom_data['product_price'], errors='coerce')
ecom_data['product_price'].fillna(ecom_data['product_price'].median(), inplace=True)

/tmp/ipykernel_11416/4174184376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ecom_data['product_price'] = pd.to_numeric(ecom_data['product_price'], errors='coerce')
/tmp/ipykernel_11416/4174184376.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['product_price'].fillna(ecom_data['product_price'].median(), inplace=True)
/tmp/ipykernel_11416/4174184376.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ecom_data['product_price'].fillna(ecom_data['product_price'].median(), inplace=True)

# Model Building

In [86]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import pickle

In [87]:
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(ecom_data['tags'])

In [88]:
text_similarity_matrix = cosine_similarity(tfidf_matrix)

In [89]:
# This matrix captures how similar two products are based on their text features (e.g., product category, brand, description).
text_similarity_matrix

array([[1.        , 0.12806664, 0.27054829, ..., 0.03668892, 0.05431277,
        0.18736993],
       [0.12806664, 1.        , 0.23737919, ..., 0.02411299, 0.08540516,
        0.31728105],
       [0.27054829, 0.23737919, 1.        , ..., 0.03489908, 0.0860038 ,
        0.27289293],
       ...,
       [0.03668892, 0.02411299, 0.03489908, ..., 1.        , 0.01193435,
        0.05126181],
       [0.05431277, 0.08540516, 0.0860038 , ..., 0.01193435, 1.        ,
        0.09961403],
       [0.18736993, 0.31728105, 0.27289293, ..., 0.05126181, 0.09961403,
        1.        ]])

In [90]:
scaler = MinMaxScaler()
normalized_prices = scaler.fit_transform(ecom_data[['product_price']].values.reshape(-1, 1))

In [91]:
price_similarity_matrix = 1 - np.abs(normalized_prices - normalized_prices.T)
price_similarity_matrix = np.nan_to_num(price_similarity_matrix)

In [92]:
# This matrix captures how similar two products are based on their prices.
print(price_similarity_matrix[:5, :5])  # Check a small sample of the matrix

[[1.         0.83633607 0.95323888 0.85925124 0.8240891 ]
 [0.83633607 1.         0.78957494 0.97708482 0.98775304]
 [0.95323888 0.78957494 1.         0.81249012 0.77732798]
 [0.85925124 0.97708482 0.81249012 1.         0.96483786]
 [0.8240891  0.98775304 0.77732798 0.96483786 1.        ]]

In [93]:
# expected range [0.0, 1.0]
print(f"Text Similarity Matrix Range: {text_similarity_matrix.min()} to {text_similarity_matrix.max()}")
print(f"Price Similarity Matrix Range: {price_similarity_matrix.min()} to {price_similarity_matrix.max()}")

Text Similarity Matrix Range: 0.0 to 1.0000000000000007
Price Similarity Matrix Range: 0.0 to 1.0

In [94]:
# The values of alpha and beta determine how much importance you give to each type of similarity when recommending products. 
# Combining text and price similarities

alpha = 0.2  # Weight for text similarity
beta = 0.8   # Weight for price similarity
combined_similarity_matrix = (alpha * text_similarity_matrix) + (beta * price_similarity_matrix)
print(f"Combined Similarity Matrix Range: {combined_similarity_matrix.min()} to {combined_similarity_matrix.max()}")

Combined Similarity Matrix Range: 0.0 to 1.0000000000000002

In [95]:
combined_similarity_matrix

array([[1.        , 0.69468218, 0.81670076, ..., 0.80197762, 0.65641724,
        0.7394983 ],
       [0.69468218, 1.        , 0.67913579, ..., 0.67925161, 0.79356687,
        0.83050075],
       [0.81670076, 0.67913579, 1.        , ..., 0.76421076, 0.62534655,
        0.719194  ],
       ...,
       [0.80197762, 0.67925161, 0.76421076, ..., 1.        , 0.65330172,
        0.71763683],
       [0.65641724, 0.79356687, 0.62534655, ..., 0.65330172, 1.        ,
        0.76345318],
       [0.7394983 , 0.83050075, 0.719194  , ..., 0.71763683, 0.76345318,
        1.        ]])

In [96]:
# Calculate the average rating and number of interactions for each product
popularity_data = users_interest_data.groupby('product_id').agg(
    average_rating=('rating', 'mean'),
    num_interactions=('product_id', 'count')
).reset_index()

# Merge popularity data with the products data
ecom_data = ecom_data.merge(popularity_data, on='product_id', how='left')

# Fill NaN values (if any) with 0
ecom_data['average_rating'].fillna(0, inplace=True)
ecom_data['num_interactions'].fillna(0, inplace=True)

/tmp/ipykernel_11416/2695288202.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['average_rating'].fillna(0, inplace=True)
/tmp/ipykernel_11416/2695288202.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ecom_data['num_interactions'].fillna(0, inplace=True)

In [97]:
# Normalize the average_rating and num_interactions using MinMaxScaler
scaler = MinMaxScaler()
ecom_data[['normalized_rating', 'normalized_interactions']] = scaler.fit_transform(
    ecom_data[['average_rating', 'num_interactions']]
)

# Calculate a combined popularity score
ecom_data['popularity_score'] = (ecom_data['normalized_rating'] + ecom_data['normalized_interactions']) / 2

In [98]:
ecom_data.sample(15)

,product_id,product_price,product_name,tags,average_rating,num_interactions,normalized_rating,normalized_interactions,popularity_score
1255,1256,22999.0,"vivo Y200 5G (Desert Gold, 128 GB)",mobile vivo 8 gb ram 128 gb rom expandable upt...,0.0,0.0,0.0,0.0,0.00
1356,1357,15990.0,"SAMSUNG Galaxy A04s (Copper, 64 GB)",mobile samsung 4 gb ram 64 gb rom 16.51 cm 6.5...,0.0,0.0,0.0,0.0,0.00
1,2,14499.0,"vivo Y22 (Starlit Blue, 64 GB)",mobile vivo 4 gb ram 64 gb rom expandable upto...,0.0,0.0,0.0,0.0,0.00
59,60,20999.0,"POCO X6 Pro 5G (Yellow, 256 GB)",mobile poco 8 gb ram 256 gb rom 16.94 cm 6.67 ...,0.0,0.0,0.0,0.0,0.00
421,422,121999.0,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Gray, 25...",mobile samsung 12 gb ram 256 gb rom 17.27 cm 6...,0.0,0.0,0.0,0.0,0.00
1311,1312,10290.0,"vivo Y28e (Breeze Green, 64 GB)",mobile vivo 4 gb ram 64 gb rom 16.66 cm 6.56 i...,3.0,1.0,0.6,0.5,0.55
699,700,34490.0,SAMSUNG 108 cm (43 inch) Ultra HD (4K) LED Sma...,television samsung operating system tizen ultr...,0.0,0.0,0.0,0.0,0.00
508,509,12478.0,"vivo Y28e 5G (Vintage Red, 128 GB)",mobile vivo 4 gb ram 128 gb rom expandable upt...,0.0,0.0,0.0,0.0,0.00
62,63,66490.0,SONY Bravia 2 138.8 cm (55 inch) Ultra HD (4K)...,television sony operating system google tv ult...,0.0,0.0,0.0,0.0,0.00
1176,1177,11399.0,"SAMSUNG Galaxy M14 5G (Smoky Teal, 128 GB)",mobile samsung 4 gb ram 128 gb rom 16.76 cm 6....,0.0,0.0,0.0,0.0,0.00
291,292,17706.0,"OPPO F21SPRO (Orange, 128 GB)",mobile oppo 8 gb ram 128 gb rom expandable upt...,0.0,0.0,0.0,0.0,0.00
1336,1337,10990.0,"SAMSUNG Galaxy M32 (Light Blue, 64 GB)",mobile samsung 4 gb ram 64 gb rom 16.51 cm 6.5...,0.0,0.0,0.0,0.0,0.00
416,417,89999.0,"SAMSUNG Galaxy S23 Ultra 5G (Green, 256 GB)",mobile samsung 12 gb ram 256 gb rom 17.27 cm 6...,0.0,0.0,0.0,0.0,0.00
516,517,9799.0,"POCO M6 5G (Orion Blue, 128 GB)",mobile poco 6 gb ram 128 gb rom expandable upt...,1.0,1.0,0.2,0.5,0.35
1461,1462,199990.0,SAMSUNG OLED 165.1 cm (65 inch) OLED Ultra HD ...,television samsung operating system tizen ultr...,0.0,0.0,0.0,0.0,0.00

In [99]:
def recommend_products_for_user(user_id, users_interest_data, products_data, similarity_matrix, top_n=10):
    # Get the list of product IDs the user is interested in
    user_interests = users_interest_data[users_interest_data['user_id'] == user_id]['product_id'].tolist()

    # Check if the user is new (i.e., no interests found)
    if not user_interests:
        print("New user detected. Providing popularity-based recommendations.")

        # Sort products based on popularity score in descending order
        popular_products = ecom_data.sort_values(by='popularity_score', ascending=False)

        # Return the top N popular products
        return popular_products['product_name'].head(top_n).tolist()
    
    # Get the indices of these products in the products_data DataFrame
    product_indices = [products_data[products_data['product_id'] == pid].index[0] for pid in user_interests]

    # Calculate the average similarity score for each product based on the user's interests
    similarity_scores = sum(similarity_matrix[idx] for idx in product_indices) / len(product_indices)

    # Sort products based on similarity scores in descending order
    product_list = sorted(list(enumerate(similarity_scores)), key=lambda x: x[1], reverse=True)

    # high threshold (e.g., 0.8), recommend products that are highly similar and low threshold (e.g., 0.1), include a wider range of products
    threshold = 0.6
    recommended_products = [
        products_data.iloc[i[0]]['product_name'] for i in product_list
        if products_data.iloc[i[0]]['product_id'] not in user_interests and i[1] > threshold
    ]

    # Return the top 5 recommended products
    print(len(recommended_products))
    return recommended_products

In [100]:
recommended_products = recommend_products_for_user(3, users_interest_data, products_data, combined_similarity_matrix)
print("Recommended Products:", random.sample(recommended_products, 10))

1396
Recommended Products: ['Apple iPhone 15 Pro Max (Black Titanium, 256 GB)', 'POCO X3 Pro (Steel Blue, 128 GB)', 'SAMSUNG Galaxy A35 5G (Awesome Navy, 256 GB)', 'LG 80 cm (32 inch) HD Ready LED Smart WebOS TV', 'vivo Y28e 5G (Breeze Green, 64 GB)', 'LG OLED A3 139 cm (55 inch) OLED Ultra HD (4K) Smart WebOS TV Alpha7 AI Processor 4K Gen6, AI Picture ...', 'SAMSUNG 7 125 cm (50 inch) Ultra HD (4K) LED Smart Tizen TV', 'vivo Y21T (Pearl White, 128 GB)', 'POCO X6 5G (Mirror Black, 256 GB)', 'SAMSUNG 7 108 cm (43 inch) Ultra HD (4K) LED Smart Tizen TV']

In [101]:
# 1 mohit ->mobiles(vivo,samsung,<25000) | speakers(jbl,sony,boAt) 
# 2 Amitesh ->mobiles(apple,oppo,samsung) | speakers(jbl) | television(SAMSUNG,LG)
# 3 Virat ->mobiles(Nokia,Google,POCO) | Kitchen Appliances(SAMSUNG,Panasonic) | television(SONY,Mi)
# 4 Roman ->mobiles(OnePlus,Google,POCO) | Kitchen Appliances(IFB,LG) | speaker(Landmark,Mivi,Portronics)

# Evaluation

In [102]:
def split_user_interests(users_interest_data, user_id):
    user_interests = users_interest_data[users_interest_data['user_id'] == user_id]['product_id'].tolist()
    train_interests, test_interests = train_test_split(user_interests, test_size=0.3, random_state=42)
    return train_interests, test_interests

In [103]:
def evaluated_recommend_products_for_user(user_id, users_interest_data, products_data, similarity_matrix):
    # Split user interests into training and testing
    train_interests, test_interests = split_user_interests(users_interest_data, user_id)
    
    # Get the indices of these products in the products_data DataFrame
    product_indices = [products_data[products_data['product_id'] == pid].index[0] for pid in train_interests]

    # Calculate the average similarity score for each product based on the user's training interests
    similarity_scores = sum(similarity_matrix[idx] for idx in product_indices) / len(product_indices)

    # Sort products based on similarity scores in descending order
    product_list = sorted(list(enumerate(similarity_scores)), key=lambda x: x[1], reverse=True)

    # Filter out products the user has already shown interest in (train set)
    # recommended_products = [
    #     products_data.iloc[i[0]]['product_id'] for i in product_list
    #     if products_data.iloc[i[0]]['product_id'] not in train_interests
    # ]
    threshold = 0.6
    recommended_products = [
        products_data.iloc[i[0]]['product_id'] for i in product_list
        if products_data.iloc[i[0]]['product_id'] not in train_interests and i[1] > threshold
    ]

    # Return the top 15 recommended product IDs
    return recommended_products[:15], test_interests

In [104]:
from sklearn.metrics import precision_score, recall_score, f1_score

def evaluate_recommendations(recommended_products, test_interests):
    y_true = [1 if pid in test_interests else 0 for pid in recommended_products]
    y_pred = [1] * len(recommended_products)

    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"F1-Score: {f1:.2f}")

In [105]:
recommended_products, test_interests = evaluated_recommend_products_for_user(1, users_interest_data, products_data, combined_similarity_matrix)
evaluate_recommendations(recommended_products, test_interests)

Precision: 0.13
Recall: 1.00
F1-Score: 0.24

In [106]:
# Precision: 0.13
# This means 13% of the recommended products were relevant. While this is still relatively low, it's an improvement compared to the previous precision of 0.07.
# Recall: 1.00
# The model is still recommending all the relevant products (those that the user might be interested in, based on their test set).
# F1-Score: 0.24
# The F1-score is still low, but it's improved from the previous 0.12. It reflects the balance between precision and recall. Since your recall is still perfect, improving precision will further raise the F1-score.
# Recall is high: Your model is successfully identifying all relevant products, but it's returning many irrelevant ones, which lowers precision.
# Precision has improved: The increase in precision is likely due to your higher emphasis on price similarity (beta = 0.8), which helps focus the recommendations on products that are more similar in price.
# Why Is Precision So Low?
# Too Many Recommendations: If your recommendation function returns a lot of products (e.g., 15), it’s possible that most of them are not relevant.
# Overemphasis on Recall: Your model might be focusing on maximizing recall by suggesting a large variety of products, but this sacrifices precision.
# Ineffective Weighting (Alpha/Beta): The weights you’ve chosen for text similarity (alpha) and price similarity (beta) may not be optimal.

In [107]:
ecom_data.head()

,product_id,product_price,product_name,tags,average_rating,num_interactions,normalized_rating,normalized_interactions,popularity_score
0,1,87999.0,"Apple iPhone 15 (Pink, 512 GB)",mobile apple 512 gb rom 15.49 cm 6.1 inch supe...,0.0,0.0,0.0,0.0,0.0
1,2,14499.0,"vivo Y22 (Starlit Blue, 64 GB)",mobile vivo 4 gb ram 64 gb rom expandable upto...,0.0,0.0,0.0,0.0,0.0
2,3,108999.0,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",mobile samsung 12 gb ram 256 gb rom 17.27 cm 6...,0.0,0.0,0.0,0.0,0.0
3,4,24790.0,"SAMSUNG Galaxy A54 5G (Awesome Violet, 128 GB)",mobile samsung 8 gb ram 128 gb rom expandable ...,0.0,0.0,0.0,0.0,0.0
4,5,8999.0,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",mobile samsung 4 gb ram 64 gb rom 16.51 cm 6.5...,0.0,0.0,0.0,0.0,0.0

In [108]:
pickle.dump(ecom_data, open("ecomprod_cleaned_data.pkl","wb"))

In [109]:
pickle.dump(combined_similarity_matrix, open("ecomprod_similarity_matrix.pkl", "wb"))