In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import ast     # TO CONVERT STRING INTO LIST
import re
import random
import string
import nltk
import nltk.corpus
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

import pickle

In [2]:
data_credits = pd.read_csv("tmdb_5000_credits.csv")
data_movies = pd.read_csv("tmdb_5000_movies.csv")

# Data Understanding

In [3]:
data_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
data_credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movie = data_movies.merge(data_credits, on="title")

In [6]:
#movie.to_csv("movie.csv", index=False)

In [7]:
movie.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
4053,0,"[{""id"": 53, ""name"": ""Thriller""}]",NaN,283384,"[{""id"": 14676, ""name"": ""series of murders""}]",en,The Calling,Detective Hazel Micallef hasn't had much to wo...,5.759493,"[{""name"": ""Darius Films"", ""id"": 5486}, {""name""...",...,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Pray for the Prey,The Calling,5.6,88,283384,"[{""cast_id"": 0, ""character"": ""Hazel Micallef"",...","[{""credit_id"": ""54e743ee9251416f5800134b"", ""de..."
1388,35000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,140823,"[{""id"": 5565, ""name"": ""biography""}, {""id"": 103...",en,Saving Mr. Banks,Author P.L. Travers travels from London to Hol...,31.957947,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,125.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Where her book ended, their story began.",Saving Mr. Banks,7.3,1226,140823,"[{""cast_id"": 13, ""character"": ""P.L. Travers"", ...","[{""credit_id"": ""52fe4a9d9251416c750e81cd"", ""de..."
222,115000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",NaN,68724,"[{""id"": 4565, ""name"": ""dystopia""}, {""id"": 1560...",en,Elysium,"In the year 2159, two classes of people exist:...",67.337670,"[{""name"": ""TriStar Pictures"", ""id"": 559}, {""na...",...,109.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,He can save us all.,Elysium,6.4,3439,68724,"[{""cast_id"": 3, ""character"": ""Max"", ""credit_id...","[{""credit_id"": ""52fe47a0c3a368484e0d17e7"", ""de..."
4527,2053648,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,14271,"[{""id"": 5970, ""name"": ""wrestling""}, {""id"": 607...",en,Beyond the Mat,Beyond the Mat is a 1999 professional wrestlin...,2.778633,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...",...,102.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Beyond the Mat,7.8,17,14271,"[{""cast_id"": 1, ""character"": ""Himself"", ""credi...","[{""credit_id"": ""58d5ec49c3a368127c03493c"", ""de..."
998,50000000,"[{""id"": 35, ""name"": ""Comedy""}]",http://www.zoolander.com/,329833,"[{""id"": 6241, ""name"": ""stupidity""}, {""id"": 966...",en,Zoolander 2,Derek and Hansel are modelling again when an o...,37.253774,"[{""name"": ""Scott Rudin Productions"", ""id"": 258...",...,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Long time no Z,Zoolander 2,4.7,797,329833,"[{""cast_id"": 0, ""character"": ""Derek Zoolander""...","[{""credit_id"": ""54ff0d5e9251410e56001a13"", ""de..."

In [8]:
movie.shape

(4809, 23)

In [9]:
movie.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,4.809000e+03,4809.000000,4809.000000,4.809000e+03,4807.000000,4809.000000,4809.000000,4809.000000
mean,2.902780e+07,57120.571429,21.491664,8.227511e+07,106.882255,6.092514,690.331670,57120.571429
std,4.070473e+07,88653.369849,31.803366,1.628379e+08,22.602535,1.193989,1234.187111,88653.369849
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.000000
25%,7.800000e+05,9012.000000,4.667230,0.000000e+00,94.000000,5.600000,54.000000,9012.000000
50%,1.500000e+07,14624.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000,14624.000000
75%,4.000000e+07,58595.000000,28.350529,9.291317e+07,118.000000,6.800000,737.000000,58595.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000,459488.000000

In [10]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [11]:
movie.duplicated().sum()

0

# Data Cleaning

In [12]:
movie = movie[["movie_id", "title", "overview", "genres", "keywords", "cast", "crew"]]

In [13]:
movie.shape

(4809, 7)

In [14]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [15]:
movie.isnull().mean()*100

movie_id    0.000000
title       0.000000
overview    0.062383
genres      0.000000
keywords    0.000000
cast        0.000000
crew        0.000000
dtype: float64

In [16]:
movie.dropna(inplace=True)

In [17]:
movie.duplicated().sum()

0

# Text Preprocessing

In [18]:
movie.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movie.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [20]:
# TO CONVERT DICTIONARY'S  VALUES INTO REQUIRED LIST
def convert(object):
    l = []
    for i in ast.literal_eval(object):
        l.append(i["name"])
    return l

movie["genres"] = movie["genres"].apply(convert)

In [21]:
movie.iloc[0].genres

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [22]:
movie.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [23]:
movie["keywords"] = movie["keywords"].apply(convert)

In [24]:
movie.iloc[0].keywords

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [25]:
movie.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [26]:
def convert2(object):
    l = []
    x = 0
    for i in ast.literal_eval(object):
        if x !=3:
            l.append(i["name"])
            x = x+1
        else:
            break
    return l

movie["cast"] = movie["cast"].apply(convert2)

In [27]:
movie.iloc[0].cast

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [28]:
#movie["crew"][0]
movie.iloc[0].crew

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [29]:
def find_director(object):
    l = []
    for i in ast.literal_eval(object):
        if i["job"] == "Director":
             l.append(i["name"])
             break
    return l

movie["crew"] = movie["crew"].apply(find_director)

In [30]:
movie.iloc[0].crew

['James Cameron']

In [31]:
movie.iloc[0].overview

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [32]:
movie["overview"] = movie["overview"].apply(lambda i: i.split())

In [33]:
movie.iloc[0].overview

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [34]:
movie.sample(15)

,movie_id,title,overview,genres,keywords,cast,crew
4232,127918,The Gatekeepers,"[In, an, unprecedented, and, candid, series, o...",[Documentary],"[israel, army, intelligence agency, shin bet]","[Ami Ayalon, Avraham Shalom, Yaakov Peri]",[Dror Moreh]
2765,16406,Dick,"[Comedy, about, two, high, school, girls, who,...",[Comedy],"[richard nixon, watergate, the white house]","[Kirsten Dunst, Michelle Williams, Will Ferrell]",[Andrew Fleming]
1393,2959,License to Wed,"[Newly, engaged,, Ben, and, Sadie, can't, wait...",[Comedy],"[new love, ten commandments, bride, bridegroom...","[Robin Williams, Mandy Moore, John Krasinski]",[Ken Kwapis]
4417,37694,Proud,"[The, true, story, of, the, only, African-Amer...",[Drama],[woman director],"[Vernel Bagneris, Marcus Chait, Michael Ciesla]",[Mary Pat Kelly]
953,928,Gremlins 2: The New Batch,"[Young, sweethearts, Billy, and, Kate, move, t...","[Comedy, Horror, Fantasy]","[new york, monster, skyscraper, mutant, restau...","[Zach Galligan, Phoebe Cates, John Glover]",[Joe Dante]
1194,11362,The Count of Monte Cristo,"[Edmond, Dantés's, life, and, plans, to, marry...","[Action, Adventure, Drama, Thriller]","[loss of lover, lover (female), ex-lover, tort...","[Jim Caviezel, Guy Pearce, Richard Harris]",[Kevin Reynolds]
1589,533,The Curse of the Were-Rabbit,"[Cheese-loving, eccentric, Wallace, and, his, ...","[Adventure, Animation, Comedy, Family]","[competition, garden, vegetable, stop motion, ...","[Peter Sallis, Helena Bonham Carter, Ralph Fie...",[Nick Park]
1999,152601,Her,"[In, the, not, so, distant, future,, Theodore,...","[Romance, Science Fiction, Drama]","[artificial intelligence, computer, love, lone...","[Joaquin Phoenix, Scarlett Johansson, Rooney M...",[Spike Jonze]
4310,98369,Blue Like Jazz,"[A, young, man, must, find, his, own, way, as,...","[Drama, Comedy]",[book store],"[Marshall Allman, Claire Holt, Tania Raymonde]",[Steve Taylor]
4761,322745,Counting,"[An, associative, collection, of, visual, impr...",[Documentary],[],[],[Jem Cohen]
1588,707,A View to a Kill,"[A, newly, developed, microchip, designed, by,...","[Adventure, Action, Thriller]","[paris, london england, france, england, san f...","[Roger Moore, Christopher Walken, Tanya Roberts]",[John Glen]
2954,86829,Inside Llewyn Davis,"[In, Greenwich, Village, in, the, early, 1960s...","[Drama, Music]","[folk music, performance, aspiring singer, new...","[Oscar Isaac, Carey Mulligan, Justin Timberlake]",[Joel Coen]
2312,1878,Fear and Loathing in Las Vegas,"[The, hallucinogenic, misadventures, of, sport...","[Adventure, Drama, Comedy]","[gonzo journalist, sweaty face, fake identity,...","[Johnny Depp, Benicio del Toro, Tobey Maguire]",[Terry Gilliam]
1732,11516,Winged Migration,"[The, cameras, of, Jacques, Perrin, fly, with,...",[Documentary],"[ocean, lake, bird, horse, parrot, owl, ornith...","[Philippe Labro, Jacques Perrin]",[Jacques Perrin]
3810,20065,Purple Violets,"[Patti, Petalson, is, a, promising, writer,, b...","[Comedy, Drama, Romance]",[independent film],"[Selma Blair, Patrick Wilson, Edward Burns]",[Edward Burns]

In [35]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4806 non-null   int64
 1   title     4806 non-null   object
 2   overview  4806 non-null   object
 3   genres    4806 non-null   object
 4   keywords  4806 non-null   object
 5   cast      4806 non-null   object
 6   crew      4806 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.4+ KB

In [36]:
# TO REMOVE THE SPACES WITHIN THE WORDS

movie["genres"] = movie["genres"].apply(lambda x: [i.replace(" ", "") for i in x])
movie["keywords"] = movie["keywords"].apply(lambda x: [i.replace(" ", "") for i in x])
movie["cast"] = movie["cast"].apply(lambda x: [i.replace(" ", "") for i in x])
movie["crew"] = movie["crew"].apply(lambda x: [i.replace(" ", "") for i in x])

In [37]:
movie.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [38]:
movie["tags"] = movie["overview"] + movie["genres"] + movie["keywords"] + movie["cast"] + movie["crew"]

In [39]:
movie["tags"][1]

['Captain',
 'Barbossa,',
 'long',
 'believed',
 'to',
 'be',
 'dead,',
 'has',
 'come',
 'back',
 'to',
 'life',
 'and',
 'is',
 'headed',
 'to',
 'the',
 'edge',
 'of',
 'the',
 'Earth',
 'with',
 'Will',
 'Turner',
 'and',
 'Elizabeth',
 'Swann.',
 'But',
 'nothing',
 'is',
 'quite',
 'as',
 'it',
 'seems.',
 'Adventure',
 'Fantasy',
 'Action',
 'ocean',
 'drugabuse',
 'exoticisland',
 'eastindiatradingcompany',
 "loveofone'slife",
 'traitor',
 'shipwreck',
 'strongwoman',
 'ship',
 'alliance',
 'calypso',
 'afterlife',
 'fighter',
 'pirate',
 'swashbuckler',
 'aftercreditsstinger',
 'JohnnyDepp',
 'OrlandoBloom',
 'KeiraKnightley',
 'GoreVerbinski']

In [40]:
movie.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [41]:
movie_data = movie[["movie_id", "title", "tags"]]
movie_data.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [42]:
# CONVERTING LIST TO STRING & CONVERTING TO LOWERCASE

movie_data["tags"] = movie_data["tags"].apply(lambda  i: " ".join(i))
movie_data["tags"] = movie_data["tags"].apply(lambda  i: i.lower())

/tmp/ipykernel_17091/1583622536.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_data["tags"] = movie_data["tags"].apply(lambda  i: " ".join(i))
/tmp/ipykernel_17091/1583622536.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_data["tags"] = movie_data["tags"].apply(lambda  i: i.lower())

In [43]:
movie_data["tags"][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [44]:
movie_data.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [45]:
#REMOVING LINKS, TOKENISATION AND REMOVING PUNCTUATIONS

def preprocessing1(text):
    te = re.sub(r'http\S+', "", text)
    tokens = word_tokenize(te)
    
    punctuations = string.punctuation
    txt = []
    for i in tokens:
        if i not in punctuations:
            txt.append(i)
    return txt

#REMOVING STOPWORDS & CONVERTING TO LOWERCASE

def preprocessing2(text):
    stopword = stopwords.words("english")
    ntxt = []
    for j in text:
        if j not in stopword:
            ntxt.append(j.lower())
    return ntxt

#STEMMING

def preprocessing3(text):
    stem = []
    Stemmer = PorterStemmer()
    for i in text:
        stem.append(Stemmer.stem(i))
    return " ".join(stem)

In [46]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /home/mohit/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [47]:
movie_data["tags"] = movie_data["tags"].apply(preprocessing1)
movie_data["tags"] = movie_data["tags"].apply(preprocessing2)
movie_data["tags"] = movie_data["tags"].apply(preprocessing3)

/tmp/ipykernel_17091/3516406077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_data["tags"] = movie_data["tags"].apply(preprocessing1)
/tmp/ipykernel_17091/3516406077.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_data["tags"] = movie_data["tags"].apply(preprocessing2)
/tmp/ipykernel_17091/3516406077.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_data["tags"] = movie_data["tags"].apply(preprocessing3)

In [48]:
movie_data["tags"][0]

'22nd centuri parapleg marin dispatch moon pandora uniqu mission becom torn follow order protect alien civil action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [49]:
movie_data.head()

,movie_id,title,tags
0,19995,Avatar,22nd centuri parapleg marin dispatch moon pand...
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believ dead come back li...
2,206647,Spectre,cryptic messag bond ’ past send trail uncov si...
3,49026,The Dark Knight Rises,follow death district attorney harvey dent bat...
4,49529,John Carter,john carter war-weari former militari captain ...

# Creating User Interest Data

In [50]:
users = pd.read_csv("users.csv")
users.head()

   user_id user_name                email
0        1     Mohit    mohit07@gmail.com
1        2   Amitesh  amitesh03@gmail.com
2        3     Virat    virat18@gmail.com
3        4     Roman    roman01@gmail.com

In [51]:
movie.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [52]:
# Display the unique genres

unique_genres = set([genre for genres_list in movie['genres'] for genre in genres_list])
print(unique_genres)

{'Adventure', 'Family', 'Horror', 'History', 'Animation', 'Documentary', 'ScienceFiction', 'Action', 'Music', 'Western', 'TVMovie', 'War', 'Fantasy', 'Drama', 'Foreign', 'Crime', 'Romance', 'Comedy', 'Thriller', 'Mystery'}

In [53]:
user_interests = {
    1: ['Mystery', 'Comedy', 'Romance', 'ScienceFiction', 'Drama'],  # Mohit
    2: ['War', 'Crime', 'Action', 'Thriller', 'Music'],              # Amitesh
    3: ['Horror', 'Animation', 'Adventure', 'Mystery', 'Action'],    # Virat
    4: ['Documentary', 'Western', 'Family', 'Comedy', 'Romance']     # Roman
}

In [54]:
# Parameters
num_users = 4
num_movies = 4806
num_interactions = 256  # Desired number of interactions

# Helper function to get movies with the most genre matches
def get_best_matching_movies(user_id, movies):
    interests = user_interests[user_id]
    
    # Calculate the number of matching genres for each movie
    movies['genre_match_count'] = movies['genres'].apply(
        lambda genres: len(set(genres).intersection(set(interests)))
    )
    
    # Filter movies with at least 2 matching genre and sort by match count
    matching_movies = movies[movies['genre_match_count'] > 2].sort_values(by='genre_match_count', ascending=False)
    
    # Return the list of movie IDs sorted by the highest genre match count
    return matching_movies['movie_id'].tolist()

# Generate Interactions
interactions = []

for _ in range(num_interactions):
    user_id = random.choice(users['user_id'])
    # Get the best matching movies for the user
    best_matching_movie_ids = get_best_matching_movies(user_id, movie)
    if not best_matching_movie_ids:
        continue  # Skip if no matching movies found
    movie_id = random.choice(best_matching_movie_ids)
    rating = random.choice([1, 2, 3, 4, 5])  # Random rating from 1 to 5

    # Add interaction
    interactions.append({
        'user_id': user_id,
        'movie_id': movie_id,
        'rating': rating
    })

# Create Interaction DataFrame
interaction_df = pd.DataFrame(interactions)

# Optionally, reset the index
interaction_df.reset_index(drop=True, inplace=True)

In [55]:
interaction_df.sample(15)

     user_id  movie_id  rating
16         2    336004       2
29         4    268171       2
94         2     72387       3
122        3     23685       5
239        2     49526       3
230        1      5178       4
224        1      5994       3
74         2     34314       3
245        1     22913       4
209        3     82702       5
31         3    168705       3
160        4      9880       5
153        2     49526       3
222        1     62764       4
43         3      9457       4

In [56]:
interaction_df.shape

(256, 3)

In [57]:
merged_df = pd.merge(interaction_df, movie, on='movie_id', how='left')

In [58]:
user_1_interactions = merged_df[merged_df['user_id'] == 1]
print(user_1_interactions.shape)
user_1_interactions.sample(20)

(72, 11)

,user_id,movie_id,rating,title,overview,genres,keywords,cast,crew,tags,genre_match_count
15,1,62764,1,Mirror Mirror,"[After, she, spends, all, her, money,, an, evi...","[Adventure, Fantasy, Drama, Comedy, ScienceFic...","[attemptedmurder, fairytale, blackmagic, cockr...","[JuliaRoberts, LilyCollins, ArmieHammer]",[TarsemSingh],"[After, she, spends, all, her, money,, an, evi...",2
133,1,9621,2,Elizabethtown,"[Drew, Baylor, is, fired, after, causing, his,...","[Comedy, Drama, Romance]","[suicide, hotelroom, suicideattempt, newlove, ...","[OrlandoBloom, KirstenDunst, SusanSarandon]",[CameronCrowe],"[Drew, Baylor, is, fired, after, causing, his,...",2
151,1,217708,3,Of Horses and Men,"[A, country, romance, about, the, human, strea...","[Drama, Romance, Comedy]","[horse, snowstorm, icelandic]","[IngvarEggertSigurðsson, CharlotteBøving, Stei...",[BenediktErlingsson],"[A, country, romance, about, the, human, strea...",2
119,1,53256,2,Three,"[Hanna, and, Simon, are, in, a, 20, year, marr...","[Romance, Drama, Comedy]","[sex, bisexual, science]","[SophieRois, SebastianSchipper, DevidStriesow]",[TomTykwer],"[Hanna, and, Simon, are, in, a, 20, year, marr...",2
88,1,9583,5,Divine Secrets of the Ya-Ya Sisterhood,"[A, mother, and, daughter, dispute, is, resolv...","[Comedy, Drama, Romance]","[secretsociety, conciliation, marriage, mother...","[SandraBullock, EllenBurstyn, FionnulaFlanagan]",[CallieKhouri],"[A, mother, and, daughter, dispute, is, resolv...",2
27,1,25113,2,The Four Seasons,"[Three, middle-aged, wealthy, couples, take, v...","[Comedy, Drama, Romance]",[],"[AlanAlda, CarolBurnett, LenCariou]",[AlanAlda],"[Three, middle-aged, wealthy, couples, take, v...",2
18,1,47607,1,Tiny Furniture,"[After, graduating, from, film, school,, Aura,...","[Romance, Comedy, Drama]","[sistersisterrelationship, malefemalerelations...","[LenaDunham, LaurieSimmons, GraceDunham]",[LenaDunham],"[After, graduating, from, film, school,, Aura,...",2
112,1,14709,5,Varsity Blues,"[In, small-town, Texas,, high, school, footbal...","[Comedy, Drama, Romance]","[americanfootball, smalltown, texas, cheerlead...","[JamesVanDerBeek, AmySmart, JonVoight]",[BrianRobbins],"[In, small-town, Texas,, high, school, footbal...",2
165,1,14474,2,The Oh in Ohio,"[Priscilla, and, Jack, appear, to, be, the, pe...","[Comedy, Drama, Romance]","[sex, adultery, depression, infidelity, nightc...","[ParkerPosey, DannyDeVito, PaulRudd]",[BillyKent],"[Priscilla, and, Jack, appear, to, be, the, pe...",2
166,1,222936,4,Aloha,"[A, celebrated, military, contractor, returns,...","[Drama, Comedy, Romance]","[lovetriangle, hawaii, satellite, military, du...","[BradleyCooper, EmmaStone, RachelMcAdams]",[CameronCrowe],"[A, celebrated, military, contractor, returns,...",2
190,1,480,5,Monsoon Wedding,"[From, an, exciting, Indian, wedding, comes, a...","[Comedy, Drama, Romance]","[childabuse, adultery, arrangedmarriage, bolly...","[NaseeruddinShah, LilleteDubey, VijayRaaz]",[MiraNair],"[From, an, exciting, Indian, wedding, comes, a...",2
242,1,9603,4,Clueless,"[Shallow,, rich, and, socially, successful, Ch...","[Comedy, Drama, Romance]","[puberty, highschool, makeamatch, spoiledchild...","[AliciaSilverstone, StaceyDash, BrittanyMurphy]",[AmyHeckerling],"[Shallow,, rich, and, socially, successful, Ch...",2
46,1,88005,4,Seeking a Friend for the End of the World,"[As, an, asteroid, nears, Earth,, a, man, find...","[Comedy, Drama, Romance, ScienceFiction]","[asteroid, roadtrip, endoftheworld, womandirec...","[SteveCarell, KeiraKnightley, ConnieBritton]",[LoreneScafaria],"[As, an, asteroid, nears, Earth,, a, man, find...",2
51,1,80271,3,LOL,"[In, a, world, connected, by, YouTube,, iTunes...","[Drama, Comedy, Romance]","[comingofage, motherdaughterrelationship, teen...","[MileyCyrus, DemiMoore, DouglasBooth]",[LisaAzuelos],"[In, a, world, connected, by, YouTube,, iTunes...",2
111,1,401,2,Garden State,"[Andrew, returns, to, his, hometown, for, the,...","[Comedy, Drama, Romance]","[newjersey, paraplegic, lossofmother, expensiv...","[ZachBraff, NataliePortman, IanHolm]",[ZachBraff],"[Andrew, returns, to, his, hometown, for, the,...",2
98,1,35219,3,The Missing Person,"[Private, detective, John, Rosow, is, hired, t...","[Comedy, Drama, Mystery, Thriller]","[detective, independentfilm, train, alcoholic,...","[MichaelShannon, AmyRyan, FrankWood]",[NoahBuschel],"[Private, detective, John, Rosow, is, hired, t...",1
8,1,712,4,Four Weddings and a Funeral,"[Four, Weddings, And, A, Funeral, is, a, Briti...","[Comedy, Drama, Romance]","[upperclass, loveatfirstsight, weddingvows, ma...","[HughGrant, AndieMacDowell, JamesFleet]",[MikeNewell],"[Four, Weddings, And, A, Funeral, is, a, Briti...",2
227,1,14578,2,Outside Providence,"[In, this, coming-of-age, comedy,, Tim, Dunphy...","[Romance, Comedy, Drama]","[suicide, sex, sexuality, college, police, cam...","[ShawnHatosy, AmySmart, AlecBaldwin]",[MichaelCorrente],"[In, this, coming-of-age, comedy,, Tim, Dunphy...",2
40,1,11130,4,The Princess Diaries 2: Royal Engagement,"[Mia, Thermopolis, is, now, a, college, gradua...","[Comedy, Drama, Family, Romance]","[coronation, duty, marriage, fallinginlove]","[AnneHathaway, JulieAndrews, HéctorElizondo]",[GarryMarshall],"[Mia, Thermopolis, is, now, a, college, gradua...",3
176,1,36549,1,Yesterday Was a Lie,"[Hoyle, a, girl, with, a, sharp, mind, and, a,...","[Drama, Mystery, ScienceFiction, Thriller]",[independentfilm],"[ChaseMasterson, JohnNewton, KipleighBrown]",[JamesKerwin],"[Hoyle, a, girl, with, a, sharp, mind, and, a,...",0

In [59]:
# mohit -> mystery, comedy, drama, romance, ScienceFiction
# amitesh -> war, crime, action, thriller, music
# virat -> horror, animation, Adventure, mystery, action
# roman -> documentary, Western, Family, comedy, romance

In [60]:
interaction_df.to_csv('movie_interaction_df.csv', index=False)

# Model Building

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import pickle

In [62]:
users_interest_data = pd.read_csv('movie_interaction_df.csv')

In [63]:
users.head()

   user_id user_name                email
0        1     Mohit    mohit07@gmail.com
1        2   Amitesh  amitesh03@gmail.com
2        3     Virat    virat18@gmail.com
3        4     Roman    roman01@gmail.com

In [64]:
users_interest_data.head()

   user_id  movie_id  rating
0        2     62835       5
1        1       508       2
2        1     10030       1
3        3     10329       5
4        1     45658       2

In [65]:
movie_data.head()

,movie_id,title,tags
0,19995,Avatar,22nd centuri parapleg marin dispatch moon pand...
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believ dead come back li...
2,206647,Spectre,cryptic messag bond ’ past send trail uncov si...
3,49026,The Dark Knight Rises,follow death district attorney harvey dent bat...
4,49529,John Carter,john carter war-weari former militari captain ...

In [66]:
movie_data.shape

(4806, 3)

In [67]:
cv = CountVectorizer(max_features=5000, stop_words="english")
tfd = TfidfVectorizer(max_features=3000)

In [68]:
vector = cv.fit_transform(movie_data["tags"]).toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [69]:
# FINDING THE DISTANCES BETWEEN THE MOVIES
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.08257228, 0.08385255, ..., 0.06282809, 0.02331262,
        0.        ],
       [0.08257228, 1.        , 0.06154575, ..., 0.02305715, 0.        ,
        0.        ],
       [0.08385255, 0.06154575, 1.        , ..., 0.04682929, 0.        ,
        0.        ],
       ...,
       [0.06282809, 0.02305715, 0.04682929, ..., 1.        , 0.05858749,
        0.04087596],
       [0.02331262, 0.        , 0.        , ..., 0.05858749, 1.        ,
        0.04550158],
       [0.        , 0.        , 0.        , ..., 0.04087596, 0.04550158,
        1.        ]])

In [70]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

[(2405, 0.2592724864350674),
 (3728, 0.25391668753850405),
 (1214, 0.2514005711827466),
 (539, 0.24404676504598818),
 (507, 0.24293289905367482)]

In [71]:
# Calculate the average rating and number of interactions for each product
popularity_data = users_interest_data.groupby('movie_id').agg(
    average_rating=('rating', 'mean'),
    num_interactions=('movie_id', 'count')
).reset_index()

# Merge popularity data with the products data
movie_data = movie_data.merge(popularity_data, on='movie_id', how='left')

# Fill NaN values (if any) with 0
# Normalize the average_rating and num_interactions using MinMaxScaler
scaler = MinMaxScaler()
movie_data[['normalized_rating', 'normalized_interactions']] = scaler.fit_transform(
    movie_data[['average_rating', 'num_interactions']]
)

# Calculate a combined popularity score
movie_data['num_interactions'].fillna(0, inplace=True)

/tmp/ipykernel_17091/2785098508.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_data['num_interactions'].fillna(0, inplace=True)

In [72]:
# Step 1: Fill NaN values in the 'num_interactions' column with 0 (if there are any)
movie_data['num_interactions'].fillna(0, inplace=True)

# Step 2: Normalize 'average_rating' and 'num_interactions' using MinMaxScaler
scaler = MinMaxScaler()

# Normalize 'average_rating' and 'num_interactions' columns
movie_data[['normalized_rating', 'normalized_interactions']] = scaler.fit_transform(
    movie_data[['average_rating', 'num_interactions']]
)

# Step 3: Calculate the combined popularity score
movie_data['popularity_score'] = (movie_data['normalized_rating'] + movie_data['normalized_interactions']) / 2

# Step 4: Fill any NaN values in 'popularity_score' (if any)
movie_data['popularity_score'].fillna(0, inplace=True)

/tmp/ipykernel_17091/3306341541.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_data['num_interactions'].fillna(0, inplace=True)
/tmp/ipykernel_17091/3306341541.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_data['popularity_score'].fillna(0, inplace=True)

In [73]:
movie_data.head()

,movie_id,title,tags,average_rating,num_interactions,normalized_rating,normalized_interactions,popularity_score
0,19995,Avatar,22nd centuri parapleg marin dispatch moon pand...,NaN,0.0,NaN,0.0,0.0000
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believ dead come back li...,NaN,0.0,NaN,0.0,0.0000
2,206647,Spectre,cryptic messag bond ’ past send trail uncov si...,NaN,0.0,NaN,0.0,0.0000
3,49026,The Dark Knight Rises,follow death district attorney harvey dent bat...,4.5,2.0,0.875,0.4,0.6375
4,49529,John Carter,john carter war-weari former militari captain ...,NaN,0.0,NaN,0.0,0.0000

In [74]:
def recommend_movies_for_user(user_id, users_interest_data, movie_data, similarity_matrix, top_n=10, threshold=0.1):
    # Get the list of movie IDs the user is interested in (assuming interest is based on 'movie_id')
    user_interests = users_interest_data[users_interest_data['user_id'] == user_id]['movie_id'].tolist()
    # print(user_interests)

    # Check if the user has any interests (if the user is new and has no interests)
    if not user_interests:
        print("New user detected. Providing popularity-based recommendations.")
        
        # Sort movies based on popularity score or other metric (assuming popularity_score exists)
        popular_movies = movie_data.sort_values(by='popularity_score', ascending=False)
        
        # Return the top N popular movies
        return popular_movies['title'].head(top_n).tolist()

    # Get the indices of the user's interested movies in the movie_data DataFrame
    movie_indices = [movie_data[movie_data['movie_id'] == movie_id].index[0] for movie_id in user_interests]
    # print(user_interests)

    # Calculate the average similarity score for each movie based on the user's interests
    # similarity_matrix: Movie similarity scores between movies
    similarity_scores = sum(similarity_matrix[idx] for idx in movie_indices) / len(movie_indices)

    # Sort movies based on similarity scores (high to low)
    movie_list = sorted(list(enumerate(similarity_scores)), key=lambda x: x[1], reverse=True)
    # print(movie_list)
    

    # Filter out movies that the user has already interacted with and apply the threshold for similarity
    recommended_movies = [
        movie_data.iloc[i[0]]['title'] for i in movie_list
        if movie_data.iloc[i[0]]['movie_id'] not in user_interests and i[1] >threshold
    ]

    # Return the top N recommended movies
    print(f"Recommending {len(recommended_movies)} movies to user {user_id}")
    return recommended_movies

In [75]:
recommended_movies = recommend_movies_for_user(1, users_interest_data, movie_data, similarity)
print("Recommended Products:", recommended_movies)

Recommending 299 movies to user 1
Recommended Products: ['Boynton Beach Club', 'The Incredibly True Adventure of Two Girls In Love', 'Lovely & Amazing', 'Housefull', 'Griff the Invisible', 'Solitary Man', 'The House of Mirth', 'My Big Fat Greek Wedding 2', 'Man on the Moon', 'Quartet', 'Living Out Loud', 'Mystic Pizza', 'Love and Other Catastrophes', 'The Importance of Being Earnest', 'The Inkwell', 'Full Frontal', 'The Spectacular Now', 'Lovely, Still', 'My Last Day Without You', 'Four Single Fathers', "Jesus' Son", 'Peggy Sue Got Married', 'The Object of My Affection', 'Sweet Charity', 'Love Me Tender', 'Never Again', 'Life During Wartime', 'Code 46', 'Summer Catch', 'Hav Plenty', 'Love Letters', 'Mumford', 'Friends with Money', 'Bride & Prejudice', "The Time Traveler's Wife", 'Admission', 'The Brothers McMullen', 'Drumline', 'The Perfect Man', 'Safety Not Guaranteed', 'Tiny Furniture', "I Don't Know How She Does It", 'Woman on Top', 'Sliding Doors', 'The Heart of Me', 'Trust the Man', 'Life or Something Like It', 'Cheri', 'Just My Luck', 'Just Wright', '200 Cigarettes', 'Walking and Talking', 'Desire', 'Dry Spell', 'About Last Night', 'The Rules of Attraction', 'The Last Song', 'Hope Springs', 'The Four Seasons', 'Love & Basketball', 'Rock of Ages', 'Love Jones', 'Shopgirl', 'Killers', 'Under the Tuscan Sun', 'One Day', '16 to Life', 'Down to You', 'Notting Hill', 'The Station Agent', 'Peaceful Warrior', 'Annie Hall', 'How to Lose Friends & Alienate People', 'Zookeeper', 'LOL', 'Going the Distance', 'Anna and the King', 'Knocked Up', 'Good bye, Lenin!', 'Seeking a Friend for the End of the World', 'New York, New York', 'Partition', 'Moonlight Mile', 'The Dirties', 'The Perfect Wave', 'Lonesome Jim', 'A Walk to Remember', 'Tin Cup', 'Phat Girlz', 'Of Horses and Men', 'The Last Five Years', 'The Salon', 'Lars and the Real Girl', "What's Eating Gilbert Grape", 'Fly Me to the Moon', 'Imagine Me & You', 'The Story of Us', 'Da Sweet Blood of Jesus', 'Eulogy', 'The Brothers Bloom', 'The Velocity of Gary', 'Elizabethtown', 'Funny Ha Ha', 'Blue Like Jazz', 'The Lake House', 'From Justin to Kelly', 'Blood and Chocolate', 'The Age of Adaline', 'Don Jon', 'Juliet and Alfa Romeo', 'Fame', 'Juno', 'New York Stories', 'Don Juan DeMarco', 'All or Nothing', 'Adam', 'All the Real Girls', 'Shallow Hal', 'Larry Crowne', 'Midnight in Paris', 'Shall We Dance?', 'Another Happy Day', 'The Holiday', 'Youth in Revolt', 'The Spanish Apartment', 'The Twilight Saga: Breaking Dawn - Part 2', 'Becoming Jane', 'The Longest Ride', 'The Women', 'Three', 'How Do You Know', 'The Brothers', 'Me and Orson Welles', 'Shakespeare in Love', 'Mary Reilly', 'Bran Nue Dae', 'Sex and the City 2', 'Veer-Zaara', 'Bandits', 'Four Weddings and a Funeral', 'Aladdin', "There's Always Woodstock", 'Nine 1/2 Weeks', 'The Cookout', 'Happy Christmas', 'Beginners', 'The Ugly Truth', 'ATL', 'Vaalu', 'Darling Companion', 'This Christmas', 'The Love Letter', 'The Good Night', 'Home for the Holidays', 'Loser', 'Outside Providence', "It's Complicated", 'You Can Count on Me', 'At First Sight', 'Jersey Girl', 'London', 'Must Love Dogs', 'Another Year', 'The Switch', "Something's Gotta Give", 'Her', '(500) Days of Summer', 'Groundhog Day', 'Riding in Cars with Boys', 'Warm Bodies', 'Iris', 'My Dog Tulip', "Your Sister's Sister", 'Saving Face', 'Inherent Vice', "Bridget Jones's Diary", 'Vamps', 'Celebrity', 'Somewhere', 'Kites', 'Purple Violets', 'Two Girls and a Guy', 'Submarine', 'Big', 'The Mirror Has Two Faces', 'The Helix... Loaded', 'Mrs. Winterbourne', 'The Wood', 'The Lucky One', 'Groove', 'The Front Page', 'Déjà Vu', 'Winnie Mandela', "It's a Wonderful Afterlife", "Can't Hardly Wait", 'There Goes My Baby', 'Forty Shades of Blue', 'Christmas Eve', 'Two Lovers', "Paris, je t'aime", 'Love & Other Drugs', 'Pink Narcissus', 'Paper Towns', 'Fatal Attraction', 'Virgin Territory', 'The Shipping News', 'Me You and Five Bucks', 'Moliere', 'The Naked Ape', 'In the Company of Men', 'Mutual Appreciation', 'Friends with Benefits', 'The Girl on the Train', 'For Your Consideration', 'Wicker Park', 'Where the Heart Is', 'Remember Me', 'Drive Me Crazy', 'Woo', 'Original Sin', 'One True Thing', 'Sex Drive', 'The New World', 'Arn: The Knight Templar', 'Heartbeeps', 'Dear John', 'On the Line', 'Georgia Rule', 'Flipped', 'American Desi', 'And So It Goes', 'Angel Eyes', 'First Knight', 'Laws of Attraction', 'Begin Again', 'Endless Love', 'The Tourist', 'Sunshine Cleaning', 'Real Women Have Curves', 'The Princess Diaries 2: Royal Engagement', 'Igby Goes Down', "She's the Man", 'Frances Ha', 'Charly', 'All the Pretty Horses', 'Redemption Road', 'Get Over It', 'You Will Meet a Tall Dark Stranger', "Winter's Tale", 'Tuck Everlasting', 'Shadowlands', 'That Awkward Moment', 'Along Came Polly', 'Not Easily Broken', 'Christmas Mail', 'Just Go with It', 'Last I Heard', 'The Wendell Baker Story', 'The Other End of the Line', 'I Dreamed of Africa', 'All Good Things', 'A Tale of Three Cities', "You Can't Take It With You", 'My Girl', 'Bubble Boy', 'Welcome to the Dollhouse', 'The Theory of Everything', 'Glitter', 'The Joneses', 'The Duchess', 'Motherhood', 'The Prince of Tides', 'Celeste & Jesse Forever', 'Volver', "It's All Gone Pete Tong", 'Wristcutters: A Love Story', 'A Home at the End of the World', 'Last Holiday', 'Secretary', 'The Names of Love', 'Fiza', 'The Best of Me', 'The Notebook', 'Me Before You', 'American Splendor', 'The Good Girl', 'Clueless', 'Choke', 'Stranger Than Fiction', 'The Virgin Suicides', '40 Days and 40 Nights', 'August', 'Kabhi Alvida Naa Kehna', 'Silver Linings Playbook', 'Twilight', "I Love You, Don't Touch Me!", 'How to Be Single', "Breakin' All the Rules", "Boys Don't Cry"]

In [76]:
# mohit -> mystery, comedy, drama, romance, ScienceFiction
# amitesh -> war, crime, action, thriller, music
# virat -> horror, animation, Adventure, mystery, action
# roman -> documentary, Western, Family, comedy, romance

In [77]:
recommended_movie_details = movie[movie['title'].isin(recommended_movies)]
recommended_movie_details.sample(20)

,movie_id,title,overview,genres,keywords,cast,crew,tags,genre_match_count
2799,6615,Lars and the Real Girl,"[Sometimes, you, find, love, where, you'd, lea...","[Comedy, Romance, Drama]","[garage, lonewolf, dyinganddeath, loss, delusi...","[RyanGosling, EmilyMortimer, PaulSchneider]",[CraigGillespie],"[Sometimes, you, find, love, where, you'd, lea...",2
2416,2752,40 Days and 40 Nights,"[Matt, Sullivan's, last, big, relationship, en...","[Comedy, Romance]","[sexaddiction, laundromat]","[JoshHartnett, ShannynSossamon, AdamTrese]",[MichaelLehmann],"[Matt, Sullivan's, last, big, relationship, en...",2
2768,9683,Bubble Boy,"[Jimmy, is, young, man, who, was, born, withou...","[Adventure, Comedy, Drama, Romance]","[lovesickness, niagarafalls, crush, youth, ill...","[JakeGyllenhaal, SwoosieKurtz, MarleyShelton]",[BlairHayes],"[Jimmy, is, young, man, who, was, born, withou...",2
1121,509,Notting Hill,"[The, British, comedy, from, director, Roger, ...","[Romance, Comedy, Drama]","[londonengland, bookshop, birthday, newlove, f...","[JuliaRoberts, HughGrant, GinaMcKee]",[RogerMichell],"[The, British, comedy, from, director, Roger, ...",2
2474,13972,The Women,"[The, story, centers, on, a, group, of, gossip...","[Comedy, Drama, Romance]","[beautysalon, divorce, womandirector]","[ClorisLeachman, IndiaEnnenga, AnnetteBening]",[DianeEnglish],"[The, story, centers, on, a, group, of, gossip...",2
1474,228205,The Longest Ride,"[The, lives, of, a, young, couple, intertwine,...","[Drama, Romance]","[basedonnovel, artstudent, cowboy, injury, bul...","[ScottEastwood, BrittRobertson, LolitaDavidovich]","[GeorgeTillman,Jr.]","[The, lives, of, a, young, couple, intertwine,...",1
4609,52032,My Dog Tulip,"[The, story, of, a, man, who, rescues, a, Germ...","[Animation, Comedy, Drama]","[humananimalrelationship, dog, germanshepherd,...","[ChristopherPlummer, LynnRedgrave, IsabellaRos...",[PaulFierlinger],"[The, story, of, a, man, who, rescues, a, Germ...",1
438,6964,Something's Gotta Give,"[Harry, Sanborn, is, an, aged, music, industry...","[Drama, Comedy, Romance]","[agedifference, ladykiller, womandirector]","[JackNicholson, DianeKeaton, KeanuReeves]",[NancyMeyers],"[Harry, Sanborn, is, an, aged, music, industry...",2
2616,57943,The Love Letter,"[20th, century, computer, games, designer, Sco...","[Comedy, Drama, Fantasy, Romance]",[],"[CampbellScott, JenniferJasonLeigh, DavidDukes]",[DanCurtis],"[20th, century, computer, games, designer, Sco...",2
1626,53113,One True Thing,"[A, career, woman, reassesses, her, parents', ...","[Drama, Romance]","[dysfunctionalfamily, cancer, deathofparent]","[MerylStreep, RenéeZellweger, WilliamHurt]",[CarlFranklin],"[A, career, woman, reassesses, her, parents', ...",1
4131,206296,The Last Five Years,"[In, New, York,, a, struggling, actress, and, ...","[Comedy, Drama, Music, Romance]","[wife, musical, marriage, divorce]","[AnnaKendrick, JeremyJordan, NatalieKnepp]",[RichardLaGravenese],"[In, New, York,, a, struggling, actress, and, ...",2
3422,38415,Bran Nue Dae,"[In, the, Summer, of, 1965, a, young, man, is,...","[Comedy, Drama, Foreign, Romance]","[musical, womandirector]","[RockyMcKenzie, GeoffreyRush, JessicaMauboy]",[RachelPerkins],"[In, the, Summer, of, 1965, a, young, man, is,...",2
3081,13689,Peaceful Warrior,"[A, chance, encounter, with, a, stranger, chan...","[Drama, Romance]",[],"[ScottMechlowicz, NickNolte, AmySmart]",[VictorSalva],"[A, chance, encounter, with, a, stranger, chan...",1
4371,49963,Walking and Talking,"[Things, have, been, tough, lately, for, Ameli...","[Comedy, Drama, Romance]","[independentfilm, womandirector]","[CatherineKeener, AnneHeche, LievSchreiber]",[NicoleHolofcener],"[Things, have, been, tough, lately, for, Ameli...",2
172,50620,The Twilight Saga: Breaking Dawn - Part 2,"[After, the, birth, of, Renesmee,, the, Cullen...","[Adventure, Fantasy, Drama, Romance]","[vampire, romance, villainess, superstrength, ...","[KristenStewart, RobertPattinson, TaylorLautner]",[BillCondon],"[After, the, birth, of, Renesmee,, the, Cullen...",1
2602,9686,New York Stories,"[Three, stories, happening, in, New, York., Th...","[Comedy, Drama, Romance]","[newyork, mother, hotel, robbery, jealousy, ob...","[WoodyAllen, MarvinChatinover, MaeQuestel]",[FrancisFordCoppola],"[Three, stories, happening, in, New, York., Th...",2
3772,11013,Secretary,"[A, young, woman,, recently, released, from, a...","[Comedy, Drama, Romance]","[suicide, clerk, fetish, sadomasochism, lawyer...","[JamesSpader, MaggieGyllenhaal, JeremyDavies]",[StevenShainberg],"[A, young, woman,, recently, released, from, a...",2
1697,812,Aladdin,"[Princess, Jasmine, grows, tired, of, being, f...","[Animation, Family, Comedy, Adventure, Fantasy...","[magic, musical, cartoon, princess, love, come...","[ScottWeinger, RobinWilliams, LindaLarkin]",[RonClements],"[Princess, Jasmine, grows, tired, of, being, f...",3
2227,171274,Inherent Vice,"[In, Los, Angeles, at, the, turn, of, the, 197...","[Comedy, Romance, Crime, Drama, Mystery]","[basedonnovel, 1970s, privateinvestigator, smo...","[JoaquinPhoenix, JoshBrolin, OwenWilson]",[PaulThomasAnderson],"[In, Los, Angeles, at, the, turn, of, the, 197...",2
4065,297621,There's Always Woodstock,"[When, Neurotic,, struggling, songwriter,, Cat...","[Romance, Comedy, Music]",[womandirector],"[AllisonMiller, JamesWolk, KateySagal]",[RitaMerson],"[When, Neurotic,, struggling, songwriter,, Cat...",2

In [78]:
# Evaluation

In [79]:
def split_user_interests(users_interest_data, user_id):
    user_interests = users_interest_data[users_interest_data['user_id'] == user_id]['movie_id'].tolist()
    train_interests, test_interests = train_test_split(user_interests, test_size=0.3, random_state=42)
    return train_interests, test_interests

In [80]:
def evaluated_recommend_products_for_user(user_id, users_interest_data, products_data, similarity_matrix):
    # Split user interests into training and testing
    train_interests, test_interests = split_user_interests(users_interest_data, user_id)
    
    # Get the indices of these products in the products_data DataFrame
    product_indices = [products_data[products_data['movie_id'] == pid].index[0] for pid in train_interests]

    # Calculate the average similarity score for each product based on the user's training interests
    similarity_scores = sum(similarity_matrix[idx] for idx in product_indices) / len(product_indices)

    # Sort products based on similarity scores in descending order
    product_list = sorted(list(enumerate(similarity_scores)), key=lambda x: x[1], reverse=True)

    threshold = 0.1
    recommended_products = [
        products_data.iloc[i[0]]['movie_id'] for i in product_list
        if products_data.iloc[i[0]]['movie_id'] not in train_interests and i[1] > threshold
    ]

    # Return the top 15 recommended product IDs
    return recommended_products[:15], test_interests

In [81]:
from sklearn.metrics import precision_score, recall_score, f1_score

def evaluate_recommendations(recommended_products, test_interests):
    y_true = [1 if pid in test_interests else 0 for pid in recommended_products]
    y_pred = [1] * len(recommended_products)

    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"F1-Score: {f1:.2f}")

In [82]:
recommended_movies, test_interests = evaluated_recommend_products_for_user(1, users_interest_data, movie_data, similarity)
evaluate_recommendations(recommended_movies, test_interests)

Precision: 0.07
Recall: 1.00
F1-Score: 0.12

In [83]:
# def recommend(movie):
#     movie_index = movie_data[movie_data["title"] == movie].index[0]     # TO GET THE INDEX VALUE OF THE SEARCHED MOVIE
#     distance = similarity[movie_index]
#     movie_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x: x[1])     # TO GET THE FIRST 5 MOVIES SIMILAR TO SEARCHED ONE
    
#     for i in movie_list:
#          print(movie_data.iloc[i[0]].title)

# recommended_movies = recommend("The Dark Knight", movie_data, similarity, top_n=10)
# print("Recommended Movies:", recommended_movies)

In [84]:
pickle.dump(movie_data, open("movie_data.pkl","wb"))

In [85]:
pickle.dump(similarity, open("movie_similarity_matrix.pkl", "wb"))